Blockchain/SideMenuViewController.h, Blockchain/SideMenuViewController.m
This should fix the order issue that @woudini noticed the enum was causing.
=> Fix refactor to be order independent

Blockchain/BCCreateWalletView.m, Blockchain/BuyBitcoinViewController.h, Blockchain/BuyBitcoinViewController.m
@woudini let me know if there is a better way to handle this.
=> Pass isNew to buy webview

Blockchain.xcodeproj/project.pbxproj, README.md, scripts/build-js.sh, scripts/install-js.sh, scripts/watch-js.sh
Copy-pasting that script every time I wanted to make a My-Wallet-v3 change was driving me crazy. I think these scripts are a good temporary improvement.
@mpfluger I changed the shell script build phase to use these too, it should work the same as before but please let me know if I missed something.
=> Shell scripts to make working with js easier

Blockchain/pt-PT.lproj/Localizable.strings
Some sentences in PT-BR were translated to PT-PT.
Some wrong translations were also corrected.
=> Localizable.strings

Blockchain/BCSecureTextField.swift, Blockchain/BackupNavigationViewController.swift, Blockchain/BackupVerifyViewController.swift, Blockchain/BackupViewController.swift, Blockchain/BackupWordsViewController.swift, Blockchain/Base.lproj/Backup.storyboard, Blockchain/SecondPasswordViewController.swift
Cleaned up some of the code and made it more consistent with the Swift syntax. I also removed the unneeded IBOutlet connection.
=> Swift refactor

Blockchain.xcodeproj/project.pbxproj, Blockchain/ExchangeConfirmViewController.m, Blockchain/ExchangeDetailView.h, Blockchain/ExchangeDetailView.m, Blockchain/ExchangeOverviewViewController.m, Blockchain/ExchangeProgressViewController.h, Blockchain/ExchangeProgressViewController.m, Blockchain/ExchangeTrade.h, Blockchain/ExchangeTrade.m, Blockchain/LocalizationConstants.h
First work in progress pull request for the Shapeshift exchange detail screen.
=> Exchange details

Blockchain/Base.lproj/Settings.storyboard, Blockchain/SettingsChangePasswordViewController.m
Minor UI fixes specific to iPhone X.
=> iPhone X fixes

Blockchain/js/wallet-ios.js
Referenced from
https://github.com/blockchain/My-Wallet-V3-Frontend/blob/42d3eaea4c4b77f1fdba07b78724d1cc76a8a49a/assets/js/services/trade-status.service.js#L29-L45
Excluding Unocoin.
=> fix(SideMenu): update logic for showing buy

Blockchain/js/wallet-ios.js
Reference to https://github.com/blockchain/My-Wallet-V3-Frontend/pull/1444/files
=> fix(Send-Eth): use timer in case transactions are dropped by network

Blockchain/AccountTableCell.h, Blockchain/AccountTableCell.m, Blockchain/AccountsAndAddressesDetailViewController.h, Blockchain/AccountsAndAddressesDetailViewController.m, Blockchain/AccountsAndAddressesNavigationController.m, Blockchain/AccountsAndAddressesViewController.h, Blockchain/AccountsAndAddressesViewController.m, Blockchain/AssetSelectorView.h, Blockchain/AssetSelectorView.m, Blockchain/BCAddressSelectionView.m, Blockchain/BCContactRequestView.m, Blockchain/BCEditAccountView.h, Blockchain/BCEditAccountView.m, Blockchain/ExchangeCreateViewController.m, Blockchain/PrivateKeyReader.h, Blockchain/PrivateKeyReader.m, Blockchain/ReceiveCoinsViewController.m, Blockchain/RootService.m, Blockchain/SendBitcoinViewController.m, Blockchain/SendEtherViewController.m, Blockchain/SideMenuViewController.m, Blockchain/TabViewController.m, Blockchain/TransactionsBitcoinViewController.m, Blockchain/TransferAllFundsBuilder.h, Blockchain/TransferAllFundsBuilder.m, Blockchain/TransferAllFundsViewController.m, Blockchain/Wallet.h, Blockchain/Wallet.m, Blockchain/js/wallet-ios.js
Contains major refactor of wallet methods to prevent duplicate code among view controllers.
=> Bch addresses

Blockchain.xcodeproj/project.pbxproj
This PR resolve the build errors on the `swift` branch.
=> fix(Project References): remove bad references

Blockchain.xcodeproj/project.pbxproj, Blockchain/BCModalView.h, Blockchain/BCWelcomeView.h, Blockchain/BCWelcomeView.m, Blockchain/Coordinators/AppCoordinator.swift, Blockchain/Coordinators/OnboardingCoordinator.swift, Blockchain/ModalPresenter.swift, Blockchain/UIDevice+Hardware.h, Blockchain/UIDevice+Hardware.m
Coordinator for onboarding flow.
Design doc for coordinator pattern: https://docs.google.com/document/d/1a8ING4q7EjTbzs9mZMep-6TivuodDRBK-RXBWXPbIWI/edit?usp=sharing
Note: please merge/review #100 before reviewing/merging this
=> feat(OnboardingCoordinator): Add OnboardingCoordinator

Blockchain.xcodeproj/project.pbxproj, Blockchain/BCCreateWalletView.h, Blockchain/BCCreateWalletView.m, Blockchain/BCWelcomeView.m, Blockchain/Blockchain-Bridging-Header.h, Blockchain/Blockchain-Prefix.pch, Blockchain/Constants.swift, Blockchain/Coordinators/OnboardingCoordinator.swift, Blockchain/LocalizationConstants.h, Blockchain/LocalizationConstants.swift, Blockchain/ModalPresenter.swift, Blockchain/Onboarding/Views/BCCreateWalletView.xib, Blockchain/Onboarding/Views/PairingInstructionsView.swift, Blockchain/Onboarding/Views/PairingInstructionsView.xib, Blockchain/RootService.m
Summary:
* Moved BCCreateWalletView into its own .xib
* Create .xib for PairingInstructionsView
* Moved welcome view route handling to OnboardingCoordinator
* Created `LocalizationConstants`
Note:
Please review/merge #102 before reviewing this
=>  refactor(Welcome): Moving welcome view route handling to OnboardingCoordinator

Blockchain.xcodeproj/project.pbxproj, Blockchain/AccountsAndAddressesDetailViewController.m, Blockchain/Alerts/AlertViewPresenter.swift, Blockchain/AppDelegate.swift, Blockchain/BCCreateAccountView.m, Blockchain/BCCreateWalletView.m, Blockchain/BCEditAccountView.m, Blockchain/BCEditAddressView.m, Blockchain/BCManualPairView.m, Blockchain/BCWebViewController.m, Blockchain/Blockchain-Bridging-Header.h, Blockchain/ContactsViewController.m, Blockchain/Coordinators/OnboardingCoordinator.swift, Blockchain/LocalizationConstants.h, Blockchain/LocalizationConstants.swift, Blockchain/MultiAddressResponse.m, Blockchain/PrivateKeyReader.m, Blockchain/ReceiveBitcoinViewController.m, Blockchain/RootService.h, Blockchain/RootService.m, Blockchain/RootServiceSwift.swift, Blockchain/SendBitcoinViewController.m, Blockchain/SendEtherViewController.m, Blockchain/TransactionDetailViewController.m, Blockchain/TransferAllFundsBuilder.m, Blockchain/UIViewController.swift, Blockchain/Wallet.m
Removing alert view presentation out of `RootService` and into `AlertViewPresenter`.
Please review/merge #103 before reviewing this.
=> refactor(AlertViewPresenter): Creating AlertViewPresenter.

Blockchain.xcodeproj/project.pbxproj, Blockchain/Blockchain-Bridging-Header.h, Blockchain/Wallet/JSContextWithDOM.swift, BlockchainTests/JSContextWithDOMTests.swift
JavaScriptCore is pure JavaScript - it lacks functions that are normally part of the DOM.
`JSContextWithDOM` is intended to define these missing functions in order to make it compatible with JS libraries that use them.
Note: `.pbxproj` file is acting strange when I add a new Swift file.
=> feat(Wallet): add JSContextWithDOM class

Blockchain.xcodeproj/project.pbxproj, Blockchain/Alerts/AlertViewPresenter+Wallet.swift, Blockchain/Alerts/AlertViewPresenter.swift, Blockchain/Authentication/AuthenticationManager.swift, Blockchain/AuthenticationCoordinator.swift, Blockchain/LocalizationConstants.swift, Blockchain/RootService.m, Blockchain/Settings/BlockchainSettings.swift
* Implement `showMobileNotice` in `AlertViewPresenter`
* Adding comment on why/when the pin is cleared on the app
=> refactor(AlertViewPresenter): Implement showMobileNotice

Blockchain/Network/NetworkManager.swift
Fixes exception related to making UI related updates on a background thread.
=> fix(network): completion should be invoked on main thread.

Blockchain.xcodeproj/project.pbxproj, Blockchain/AV/AVCaptureDeviceInput.swift, Blockchain/AccountsAndAddressesViewController.m, Blockchain/Alerts/AlertViewPresenter.swift, Blockchain/AppDelegate.swift, Blockchain/Authentication/AuthenticationCoordinator.swift, Blockchain/Authentication/AuthenticationManager.swift, Blockchain/Authentication/Models/PasscodePayload.swift, Blockchain/Authentication/Views/PasswordRequiredView.swift, Blockchain/Blockchain-Bridging-Header.h, Blockchain/BuyBitcoinNavigationController.m, Blockchain/Coordinators/OnboardingCoordinator.swift, Blockchain/LocalizationConstants.h, Blockchain/LocalizationConstants.swift, Blockchain/PairingCodeParser.m, Blockchain/QRCodeScannerSendViewController.m, Blockchain/RootService.h, Blockchain/RootService.m, Blockchain/SendBitcoinViewController.m, Blockchain/Wallet.h, Blockchain/Wallet.m, Blockchain/Wallet/WalletAuthDelegate.swift, Blockchain/Wallet/WalletManager.swift
Tested that paring a wallet via QR code works. Will work on 2FA flow next.
=> refactor(pairing): move wallet pairing via QR code

Blockchain.xcodeproj/project.pbxproj, Blockchain/AppDelegate.swift, Blockchain/Authentication/AuthenticationCoordinator.swift, Blockchain/Blockchain-Prefix.pch, Blockchain/Constants.swift, Blockchain/Extensions/Strings.swift, Blockchain/Extensions/UIApplication.swift, Blockchain/Extensions/URLs.swift, Blockchain/RootService.h, Blockchain/RootService.m, Blockchain/URL/BitcoinURLPayload.swift, Blockchain/Wallet/WalletManager.swift, BlockchainTests/URL/BitcoinURLPayloadTests.swift
Also created `BitcoinURLPayload` + unit tests to encapsulate the URL request "bitcoin://". I still need to migrate `showType` which I'll do in another PR.
=> refactor(AppDelegate): Migrate application:openUrl:options

Blockchain.xcodeproj/project.pbxproj, Blockchain/AccountsAndAddressesNavigationController.h, Blockchain/AccountsAndAddressesNavigationController.m, Blockchain/RootService.m, Blockchain/Wallet/WalletAddressesDelegate.swift, Blockchain/Wallet/WalletManager.swift
Reattempt of https://github.com/blockchain/My-Wallet-V3-iOS/pull/144
=> refactor(WalletAddressesDelegate): add wallet addresses delegate

Blockchain/Trade.swift, Blockchain/Wallet/WalletManager.swift
To address comment in https://github.com/blockchain/My-Wallet-V3-iOS/pull/149
=> refactor(BuySell): setup trade from dictionary in wallet delegate method

Blockchain/Alerts/AlertViewPresenter.swift, Blockchain/Authentication/AuthenticationCoordinator+Biometrics.swift, Blockchain/Authentication/AuthenticationCoordinator.swift, Blockchain/Authentication/AuthenticationManager.swift, Blockchain/Authentication/Models/AuthenticationCoordinator+Pin.swift, Blockchain/Extensions/UIApplication+Suspend.h, Blockchain/Extensions/UIApplication+Suspend.m, Blockchain/LocalizationConstants.h, Blockchain/LocalizationConstants.swift, Blockchain/Pin/Pin.swift, Blockchain/RootService.h, Blockchain/RootService.m, Blockchain/SettingsTableViewController.m, Blockchain/WalletSetupViewController.h, Blockchain/WalletSetupViewController.m
Also fixed `UIApplication.shared.suspend` loop.
=> refactor(touchID): migrate touch ID away from RootService.

Blockchain.xcodeproj/project.pbxproj, Blockchain/AV/SoundManager.swift, Blockchain/Blockchain-Prefix.pch, Blockchain/RootService.h, Blockchain/RootService.m
Created `SoundManager` for playing sounds in the app. Tested that `SoundManager.shared.playBeep()` works.
Looks like we're not using `playAlert()` at all though (I went ahead and migrated that as well).
=> refactor(SoundManager): creating SoundManager.

Blockchain/AppDelegate.swift, Blockchain/Authentication/AuthenticationCoordinator.swift, Blockchain/Notifications/PushNotificationManager.swift, Blockchain/RootService.m
Also removed `LegacyPushNotificationManager`
=> refactor(push): migrate didReceiveRemoteNotification.

Blockchain/Wallet/WalletManager.swift
* Not necessary to do conditional casting for `NSMutableDictionary` since it will always succeed
* Updated signature to `didCompleteTrade(_ tradeDict: [AnyHashable : Any]!)` so that it matches the signature defined in `WalletDelegate`
=> fix(warning): fixing warnings in WalletManager.

Blockchain/BCCreateAccountView.m, Blockchain/BCEditAccountView.m, Blockchain/LocalizationConstants.h, Blockchain/LocalizationConstants.swift, Blockchain/RootService.m, Blockchain/Wallet.h, Blockchain/Wallet.m, Blockchain/js/wallet-ios.js
This PR migrates `alertUserOfInvalidAccountName` from `Root Service` to `BCCreateAccountView`.
=> Migrate alertUserOfInvalidAccountName

Blockchain/ReceiveBitcoinViewController.m, Blockchain/SendBitcoinViewController.m, Blockchain/URL/BitcoinURLPayload.swift, Blockchain/Wallet.m, BlockchainTests/URL/BitcoinURLPayloadTests.swift
There are still a couple remaining but those methods still have to be migrated
=> refactor(RootService): remove app references.

Blockchain/Blockchain-Prefix.pch, Blockchain/LocalizationConstants.h, Blockchain/SettingsTableViewController.m
Note that this will be merged into `release` and not `dev`.
=> update(About): add cookie policy and update other About URLs

PinEntry/Classes/PEViewController.m
- Adds iPhone X support to the **Pin Screen**.
```
iPhone X Support for Pin Screen (#221)
```
=> iPhone X Support for Pin Screen

Blockchain.xcodeproj/project.pbxproj, Blockchain/AV/AVCaptureDeviceInput.swift, Blockchain/Authentication/AuthenticationCoordinator.swift, Blockchain/SendBitcoinViewController.m, Blockchain/URL/AssetURLPayload.swift, Blockchain/URL/AssetURLPayloadFactory.swift, Blockchain/URL/BIP21URI.swift, Blockchain/URL/BitcoinCashURLPayload.swift, Blockchain/URL/BitcoinURLPayload.swift, BlockchainTests/URL/AssetURLPayloadFactoryTests.swift, BlockchainTests/URL/BitcoinURLPayloadTests.swift
* Created `AssetURLPayload` protocol
* Created `BIP21URI` protocol which is implemented by BitcoinURLPayload and BitcoinCashURLPayload.
* Also made an adjustment to the convenience initializer where it will return nil if the provided URL does not contain an address (BIP21 requires that an address be specified)
=>  feature(AssetURLPayload): abstractions for AssetURLPayload and BIP 21.

Blockchain/WalletSetupViewController.m
- Adds iPhone X support to the **Wallet Setup Screen**.
```
iPhone X Support for Wallet Setup Screen (#223)
```
=> iPhone X Support for Wallet Setup Screen

Blockchain.xcodeproj/project.pbxproj, Blockchain/AppDelegate.swift, Blockchain/Blockchain-Prefix.pch, Blockchain/CardsViewController.m, Blockchain/Coordinators/AppCoordinator.swift, Blockchain/DashboardViewController.m, Blockchain/Extensions/UINavigationBar+TitleAttributes.swift, Blockchain/SideMenuViewController.m, Blockchain/TabController.xib, Blockchain/TabControllerManager+Nib.swift, Blockchain/TabControllerManager.h, Blockchain/TabControllerManager.m, Blockchain/TabViewController.h, Blockchain/TabViewController.m, Blockchain/Transactions.xib, Blockchain/TransactionsBitcoinViewController.h, Blockchain/TransactionsBitcoinViewController.m, Blockchain/TransactionsViewController.m
- Adds iPhone X support to the **Dashboard Screen**.
- Adds iPhone X support to the **Tab View Controller**.
```
iPhone X Support for Dashboard (#231)
```
=> iPhone X Support for Dashboard

Blockchain/BCCreateWalletView.m, Blockchain/Coordinators/OnboardingCoordinator.swift
* fixed issue where busy view was not presented
* fixed issue where UITextField was being hidden after tapping on "Continue" when trying to recover funds
=> fix(recover): Fix recover fund loading and text field bug

Blockchain.xcodeproj/project.pbxproj, Blockchain/AppDelegate.swift, Blockchain/Blockchain-Prefix.pch, Blockchain/CardsViewController.m, Blockchain/Coordinators/AppCoordinator.swift, Blockchain/DashboardViewController.m, Blockchain/Extensions/UINavigationBar+TitleAttributes.swift, Blockchain/SideMenuViewController.m, Blockchain/TabController.xib, Blockchain/TabControllerManager+Nib.swift, Blockchain/TabControllerManager.h, Blockchain/TabControllerManager.m, Blockchain/TabViewController.h, Blockchain/TabViewController.m, Blockchain/Transactions.xib, Blockchain/TransactionsBitcoinViewController.h, Blockchain/TransactionsBitcoinViewController.m, Blockchain/TransactionsViewController.m
Using `dev` as the base branch for the remaining iPhone X support.
=> iPhone X into Dev

Blockchain/Base.lproj/SendCoins.xib, Blockchain/SendBitcoinViewController.h, Blockchain/SendBitcoinViewController.m, Blockchain/SendEtherViewController.m
- Adds iPhone X support to the **Send Screen**.
```
iPhone X Support for Send Screen (#242)
```
=> iPhone X Support for Send Screen

Blockchain/Authentication/Views/PasswordRequiredView.swift, Blockchain/BackupVerifyViewController.swift, Blockchain/BackupViewController.swift, Blockchain/BackupWordsViewController.swift, Blockchain/Constants.swift, Blockchain/Coordinators/KeyImportCoordinator.swift, Blockchain/Coordinators/OnboardingCoordinator.swift, Blockchain/Coordinators/TransferAllCoordinator.swift, Blockchain/LocalizationConstants.swift, Blockchain/Network/CertificatePinner.swift, Blockchain/Network/Extensions/BlockchainAPI+Payload.swift, Blockchain/NumberFormatter+Assets.swift, Blockchain/Onboarding/Views/PairingInstructionsView.swift, Blockchain/Settings/BlockchainSettings.swift, Blockchain/Wallet/WalletBuySellDelegate.swift, Blockchain/Wallet/WalletSendEtherDelegate.swift, Blockchain/Wallet/WalletWatchOnlyDelegate.swift, BlockchainTests/NumberFormatter+AssetsTests.swift
Fixing various swiftlint warnings:
* Trailing whitespace violation
* Variable naming related violations
* Nesting violations
* Number of chars in a single line violations
=> fix(warnings): fix various swiftlint warnings.

Blockchain/ReceiveBitcoinViewController.m, Blockchain/ReceiveEtherViewController.m
- Adds iPhone X support to the **Request Screen**.
```
iPhone X Support for Request Screen (#249)
```
=> iPhone X Support for Request Screen

Blockchain/SettingsNavigationController.m
iPhone X Screenshots:
iPhone 5S Screenshots:
=> iPhone X Support for Settings Screen.

Blockchain/Base.lproj/Settings.storyboard
- Adds iPhone X support to the **Two-Step Verification Screen**.
```
iPhone X Support for Two-Step Verification Screen (#254)
```
=> iPhone X Support for Two-Step Verification Screen

Blockchain/Blockchain-Prefix.pch, Blockchain/TransactionDetailNavigationController.m
=> iPhone X support for TX details screen

Blockchain/BackupNavigationViewController.swift, Blockchain/BackupViewController.swift, Blockchain/BackupWordsViewController.swift
Changes:
- Fix top bar height and header label
- Fix bottom buttons
Notes:
- The chevron button and maybe also the close button have a pretty rigid frame and are not correctly positioned right now, may consider refactoring this to make it consistent across all navigation controllers even though it will likely be trashed with a new design later.
=> Backup iphone x

Blockchain/BCLine.m, Blockchain/BCNavigationController.m, Blockchain/ConfirmStateViewController.m, Blockchain/ContinueButtonInputAccessoryView.m, Blockchain/ExchangeConfirmViewController.m, Blockchain/ExchangeCreateViewController.m, Blockchain/ExchangeDetailView.m, Blockchain/ExchangeModalView.m, Blockchain/ExchangeOverviewViewController.m, Blockchain/ExchangeProgressViewController.m, Blockchain/StateSelectorViewController.m
Includes iPhone X support for:
* select your state confirm screen
* state selection screen
* exchange create screen
* exchange confirm screen
* exchange overview screen
* exchange progress screen
* exchange modal screen (note that the title view is still off, this is due to `BCModalViewController` not being ported yet, will address in another PR)
Screenshots:
iPhone X:
iPhone 5s:
=> iPhone X support for Exchange Screens

Blockchain.xcodeproj/project.pbxproj, Blockchain/Addresses/AssetAddressRepository.swift, Blockchain/AssetTypeLegacyHelper.swift, Blockchain/Network/Extensions/BlockchainAPI+URL.swift, Blockchain/Network/Extensions/BlockchainAPI+URLSuffix.swift, Blockchain/TabControllerManager.m, Blockchain/TransactionDetailNavigationController.m, Blockchain/TransactionDetailViewModel.m, BlockchainTests/Network/BlockchainAPI+URLSuffixTests.swift, PinEntry/Classes/PEPinEntryController.m
Tested and make sure that BTC, ETH, and BCH share action in the TX detail direct to the correct URL.
=> fix(tx_detail): make sure share action for an ether transaction directs to etherscan

Blockchain/TransactionsBitcoinCashViewController.m, Blockchain/TransactionsBitcoinViewController.m, Blockchain/TransactionsEtherViewController.m
- Correctly resizes the table view's frame such that the last transaction in the list is visible.
- Moves view lifecycle methods to top of file.
=> fix(Transactions): correctly resize table view

Blockchain.xcodeproj/project.pbxproj, Blockchain/BCAddressSelectionView.m, Blockchain/ExchangeCreateViewController.m, Blockchain/TransferAllFundsViewController.m
- Correctly sizes the main view and the tableview in `BCAddressSelectionView.m`.
- Removes additional top spacing in `ExchangeCreateViewController.m` and `TransferAllFundsViewController.m`.
- Correctly sorts the XIB files inside their group.
=>  fix(Address Selection): correctly size views

Blockchain/BuyBitcoinViewController.m
- Adds iPhone X support to the **Buy/Sell web view**.
=> feat(Buy Bitcoin): add iPhone X support

Blockchain/PairingCodeParser.m
The title view did not compensate for the safe area inset. This PR fixes that by computing the safe area inset top and adjusting the view's height and corresponding subviews' positions.
=> fix(Automatic Pairing): adjust position of title view on the automatic pairing screen for iPhone X

Blockchain/Base.lproj/Settings.storyboard, Blockchain/en.lproj/Settings.strings
- Updates the description for two-factor authentication to reflect that Google authenticator is not supported on mobile.
Translations need to be updated for this PR.
=> chore(Settings): update copy for 2FA description

Blockchain.xcodeproj/project.pbxproj, Blockchain/AccountsAndAddressesNavigationController.m, Blockchain/AppDelegate.swift, Blockchain/AppReviewPrompt/AppReviewPrompt.swift, Blockchain/Blockchain-Prefix.pch, Blockchain/DebugTableViewController.m, Blockchain/Extensions/UserDefaults.swift, Blockchain/LocalizationConstants.h, Blockchain/LocalizationConstants.swift, Blockchain/ReceiveBitcoinViewController.m, Blockchain/SendBitcoinViewController.m, Blockchain/Settings/BlockchainSettings.swift
- Extracts the app review logic into a separate component.
=> refactor(App Review): extract app review logic into separate component

Blockchain/AccountsAndAddressesNavigationController.m, Blockchain/AccountsAndAddressesViewController.m, Blockchain/BCModalView.m, Blockchain/BCWelcomeView.m, Blockchain/Constants.swift, Blockchain/ReceiveBitcoinViewController.m, Blockchain/ReceiveEtherViewController.m, Blockchain/SendBitcoinViewController.m, Blockchain/SendEtherViewController.m, Blockchain/TransferAllFundsViewController.m
- Uses the new UIView frame extension.
=> Use UIView Safe Area Frame Extension

Blockchain.xcodeproj/project.pbxproj
- Adds group for Buy/Sell and KYC collaboration.
Hopefully this makes it easier to start working on Buy/Sell and KYC in parallel.
=> chore(Project): create group for Buy & Sell feature

Blockchain.xcodeproj/project.pbxproj, README.md
Also updates README build instructions.
=> fix(Project): allow building without Fabric keys

Blockchain/ExchangeCreateViewController.m
Will create a ticket to add a `throw` somewhere to catch these kinds of oversights.
=> fix(Exchange): pass in enum instead of string

Blockchain/TabController.xib
Fixes an issue that could potentially cause the tab bar to be improperly formatted on iPhone X
=> fix(TabBar): Fix iPhoneX TabBar constraints

Blockchain.xcodeproj/project.pbxproj
- Adds the KYC source files to the `BlockchainTests` target.
=> fix(KYC): add source files to BlockchainTests target

Blockchain/Extensions/Strings.swift, Blockchain/Modal Content Views/BCCreateAccountView.m, Blockchain/Modal Content Views/BCCreateWalletView.m, Blockchain/Network/Models/WalletServiceError.swift
Fixes an issue creating and recovering wallets when using an invalid email address. Will need to incorporate changes from https://github.com/blockchain/My-Wallet-V3-iOS/pull/322 before merging.
=> fix(Recover Wallet): Update email validation

Blockchain/Extensions/NSAttributedString+Conveniences.swift, Blockchain/KYC/Address/KYCAddressDetailViewController.swift, Blockchain/KYC/Search/DataProvider/LocationDataProvider.swift
Fixing swiftlint errors which were causing compiling/building errors on `kyc`.
=> fix(Swiftlint): fix swiftlint errors

Blockchain.xcodeproj/project.pbxproj, Blockchain/View Controllers/Settings/SettingsViewController.swift
Fixes unit tests by adding appropriate target memberships
Run tests, they should pass
=> fix(targets): Update target memberships

Blockchain.xcodeproj/project.pbxproj
Fixing failed unit tests.
There were a couple of `Personal*.swift` files that were duplicated in `BlockchainTests` target. Fix was to remove from the target followed by readding it.
Pull in this branch and run unit tests.
N/A
- [] Areas of technical debt are marked with a `// TICKET:` comment that includes a ticket number.
=> fix(Unit Tests): removing duplicate files.

README.md
Adds RETAIL_CORE_URL instructions to readme
=> chore(readme): Add config var to readme

Blockchain.xcodeproj/project.pbxproj
Restore the ability to use the dev environment and settings.
Create a new scheme in Xcode [Blockchain (Dev) for example], and configure it to use the Debug Dev build configuration. Also make sure to enable testing by adding the BlockchainTests target to the Tests list under the scheme's Test options.
=> chore(Project): add dev environment scheme

Blockchain/Localization/Base.lproj/Settings.storyboard
*Describe in detail how you achieved the objective*
Fixes a key-coding issue by removing a (no longer used) inspectable var from Interface Builder.
=> fix(KYC): Fix IBInspectable

PULL_REQUEST_TEMPLATE.md
Removing this section in the PR template since ticket issues can just be referenced in the commit message and PR titles.
=> style(PR Template): removing related infomation section.

Blockchain.xcodeproj/project.pbxproj
Likely from a merge conflict. Multiple files of the same type were added to the test target.
1. Build and run the tests target
2. The tests should pass
=> fix(Tests) - Fixes broken tests.

Blockchain.xcodeproj/project.pbxproj, Blockchain/KYC/Storyboards/Base.lproj/KYCAddressController.storyboard, Blockchain/KYC/Storyboards/Base.lproj/KYCPersonalDetailsController.storyboard, Blockchain/KYC/Storyboards/KYCConfirmPhoneNumberController.storyboard, Blockchain/KYC/Storyboards/KYCCountrySelectionController.storyboard, Blockchain/KYC/Storyboards/KYCEnterPhoneNumberController.storyboard, Blockchain/KYC/Storyboards/KYCInformationController.storyboard, Blockchain/KYC/Storyboards/KYCVerifyIdentityController.storyboard, Blockchain/KYC/Storyboards/KYCWelcomeController.storyboard, Blockchain/LocalizationConstants.swift
Revise copy in the UI to match that specified by the designs.
Updated colors, copy and fonts.
Take the KYC flow for a spin.
=> fix(KYC): IOS-1233 update copy in KYC flow

PULL_REQUEST_TEMPLATE.md
To remind developers to compare with design for accuracy.
Added a design assessment to Screenshot section.
Open a PR and see that the template has changed to include a design assessment
N/A
=> style(PR Template): add design assessment to screenshot section

Blockchain/Homebrew/Authentication/NabuAuthenticationService.swift
Check that the cached Nabu session token user_id matches the current wallet nabu user_id.
We need to check that the cached session token matches the current wallet nabu user_id so that when you log-out and create a new wallet, the cached session token for the previous wallet/user is not used.
1. Create a wallet
2. Go through KYC and complete all the steps
3. Log-out
4. Create a new wallet
5. Try to go through KYC again (verify that going through KYC will start the process from the start)
N/A
=> fix(KYC): IOS-1269 avoid using cached token if user ID does not match.

Blockchain/KYC/KYCPageViewFactory.swift, Blockchain/KYC/Mobile Number/KYCConfirmPhoneNumberController.swift, Blockchain/KYC/Mobile Number/KYCEnterPhoneNumberController.swift, Blockchain/KYC/Mobile Number/KYCVerifyPhoneNumberPresenter.swift, Blockchain/KYC/Storyboards/KYCConfirmPhoneNumberController.storyboard, Blockchain/KYC/Storyboards/KYCEnterPhoneNumberController.storyboard, Blockchain/LocalizationConstants.swift
Polish tasks for KYC phone number verification
Changes:
* showing correct number on enter confirmation screen (IOS-1265)
* improving error handling by showing more sensible error messages in the alert
* using PrimaryButtonContainer (PrimaryButton is deprecated) which shows the loading view 
Pull in changes and test the phone number confirmation flow.
N/A
=> fix(KYC): IOS-1247 Polish tasks for KYC phone number verification

Blockchain.xcodeproj/project.pbxproj
Delete recovered references.
Deleted recovered references. `TradingPair.swift` seemed to have a duplicate entry.
Make sure the project compiles.
N/A
=> chore(Project): delete recovered references

Blockchain/KYC/Storyboards/Base.lproj/KYCApplicationCompleteController.storyboard
Update the copy on the _Application Completed_ screen according to the designs.
=> fix(KYC): update copy on application completed screen (IOS-1267)

Blockchain/Coordinators/AppCoordinator.swift, Blockchain/Side Menu/SideMenuItem.swift, Blockchain/Side Menu/SideMenuPresenter.swift
Remove "Debug KYC" side menu option since this is no longer needed (you can enter KYC by tapping on "Exchange" or by tapping "Identity Verification" in the settings screen)
=> fix(KYC): remove debug KYC side menu option.

Blockchain/Coordinators/ExchangeCoordinator.swift
So that the Nabu authentication session token is shared across areas that need it.
=> fix(Exchange): always use shared NabuAuthenticationService.

Blockchain/Models/HDNode.m, Blockchain/Models/KeyPair.m
Reduce console noise.
Removed `DLog`s called often in the app.
Run the app, see a cleaner console.
N/A
=> clean(Models): remove logs to reduce console noise

Blockchain/Blockchain-Info.plist
Catch `dev` up to `release` and resolve merge conflict.
Merged `release` into `dev` and resolved `Blockchain-Info.plist` merge conflict.
Run, it should compile and if you go to exchange socket conversion messages should work.
N/A
=> update(Development): merge release branch into dev

PULL_REQUEST_TEMPLATE.md
Improve documentation in the project.
Added checkbox for sufficient documentation to PR template.
=> feat(PR Template): add checkbox for documentation

Blockchain/Homebrew/Exchange/ExchangeDetailCoordinator.swift
Changing `Estimated Fees` to just `Fees`
N/A
N/A
=> fix(HB): IOS-1352 - Changing `Estimated Fees` to just `Fees`.

Blockchain/Settings/Settings+Helpers.swift, Blockchain/Settings/Settings+Table.swift, Blockchain/View Controllers/Settings/SettingsViewController.swift
Fixes issue where badge can still flicker.
Fixes issue where badge can still flicker.
Open settings, check the identity verification badge. Please test with different users with different KYC statuses.
=> fix(Settings): fix identity verification badge flickering (IOS-1286)

Blockchain/Coordinators/ExchangeCoordinator.swift, Blockchain/Side Menu/SideMenuPresenter.swift
Approved users should see the exchange regardless of their locale. 
Users could go through KYC and get approved but then be located in a region that is technically not supported. If they are approved, they should be able to submit exchanges regardless. 
1. Build and run in staging
2. Sign into the account listed in the ticket (or DM me)
3. Go to the side menu. You should see `Exchange`
4. Tap `Exchange`. You should see homebrew.
N/A
=> fix(HB): IOS-1370

Blockchain/Data/BlockchainDataRepository.swift, Blockchain/Side Menu/SideMenuPresenter.swift
Sorting countries alphabetically.
KYC country selection screen
=> fix(KYC): sort countries alphabetically (IOS-1332)

Blockchain/Homebrew/Exchange/ExchangeDetailCoordinator.swift, Blockchain/Homebrew/Exchange/Views/Cells/NewOrderTableViewCell.xib, Blockchain/KYC/Storyboards/Base.lproj/KYCCountrySelectionController.storyboard
**Copy changes to**:
* country selection screen (change header and subheader)
* exchange list screen (change to "Start a new exchange")
* exchange lock screen (removing footer)
=> fix(Copy): update copy changes (IOS-1495)
