blockchain/My-Wallet-V3-iOS

Blockchain/Blockchain-Prefix.pch
Blockchain/BuyBitcoinViewController.m

@woudini this handler will be called when the user presses the "See Your Bitcoin" button in the modal that's shown after a trade is completed. The intent is to take them to the native transaction details screen rather than the one in the webview. Could you implement that part? I'll pass the tx hash with to the completion handler.

Add showTx handler to buy webview

---

Blockchain/BuyBitcoinViewController.m

Thank you @jtormey for helping out with this one. My favorite parts were:
1. Commenting out bitcoin network
2. When fixing the autofocus worked but broke scroll entirely
3. When @jtormey made an MVP to test locally
4. When it worked on iphone safari but not ios webview
5. When I didn't have write access to push the changes to My-Wallet-V3-iOS @tuzzolo 
Thanks again @jtormey

Enable scrolling in iframe and fix focus jump

---

Blockchain/ExchangeCreateViewController.m

There's still a hard-to-find issue with this - sometimes when changing the amounts in fields you get different amounts (amounts you may not have typed in). This may be related to the async operation `getApproximateQuote` or an incorrect assignment to the pointers `btcField`, `bchField`, and `ethField`.

Fix exchange

---

Blockchain.xcodeproj/project.pbxproj

Until the continuous deployment pipeline is setup, the certificate will only be fetched when installing the application. Additionally, the build phase will check whether the `Cert` directory exists and create it if necessary.

fix(Build Phases): fetch certificate when installing only

---

Blockchain.xcodeproj/project.pbxproj
Blockchain/Blockchain-Prefix.pch
Blockchain/DashboardViewController.m
Blockchain/Extensions/UserDefaults.swift
Blockchain/RootService.h
Blockchain/RootService.m
Blockchain/RootServiceSwift.swift
Blockchain/Settings/BlockchainSettings.swift

`BlockchainSettings` is a wrapper around user-specific settings that is saved to `UserDefaults`. As part of the refactor, let's move most settings from `NSUserDefaults` into this class so that the application-level doesn't have to reference string keys.
I just moved a few properties for now, but other keys should pretty much have the same pattern.
Note: this PR is against `delegate` for now, but should be against `swift` once the `swift` branch is up-to-date (@achtenhagen is currently updating that branch).

refactor(NSUserDefaults) create BlockchainSettings to wrap NSUserDefaults.

---

Blockchain/NSNumberFormatter+Currencies.m

To display `$0.00` instead of `$.00`

fix(Dashboard): always show at least one integer digit for fiat balance

---

Blockchain/AccountTableCell.m
Blockchain/BCAddressSelectionView.m
Blockchain/BCCreateAccountView.m
Blockchain/BCCreateWalletView.m
Blockchain/BCEditAccountView.m
Blockchain/BCEditAddressView.m
Blockchain/BCModalView.m
Blockchain/BCModalViewController.m
Blockchain/Blockchain-Prefix.pch
Blockchain/Constants.swift
Blockchain/ModalPresenter.swift
Blockchain/QRCodeScannerSendViewController.m
Blockchain/ReceiveBitcoinViewController.m
Blockchain/RootService.h
Blockchain/RootService.m
Blockchain/SendBitcoinViewController.m
Blockchain/SendEtherViewController.m
Blockchain/TabViewController.m
Blockchain/TransactionsBitcoinCashViewController.m
Blockchain/TransactionsBitcoinViewController.m

Summary of changes:
* Using ModalPresenter to show/close BCModalViews.
* Moving animation constants to `Constants.swift`.
* Created `ConstantsObjcBridge` so that values within `Constants.swift` can be accessed.
* Commented out show/close `BCModalView` related code in RootService.
* Added a few TODOs (busyView related), will address those in a separate PR.
Notes:
* Please review/merge #101 before reviewing this

refactor(BCModalView): using ModalPresenter to show/close BCModalViews

---

Blockchain.xcodeproj/project.pbxproj
Blockchain/BCCreateWalletView.m
Blockchain/BCEditAccountView.m
Blockchain/BCEditAddressView.m
Blockchain/BCFadeView.h
Blockchain/BCFadeView.m
Blockchain/ContactDetailViewController.m
Blockchain/ContactsViewController.m
Blockchain/Coordinators/AppCoordinator.swift
Blockchain/ExchangeOverviewViewController.m
Blockchain/Loading/BCFadeView.xib
Blockchain/LoadingViewPresenter.swift
Blockchain/LocalizationConstants.swift
Blockchain/ModalPresenter.swift
Blockchain/PairingCodeParser.m
Blockchain/PrivateKeyReader.m
Blockchain/ReceiveBitcoinViewController.m
Blockchain/RootService.h
Blockchain/RootService.m
Blockchain/RootServiceSwift.swift
Blockchain/SendBitcoinViewController.m
Blockchain/TransactionsBitcoinCashViewController.m
Blockchain/TransactionsBitcoinViewController.m
Blockchain/TransactionsEtherViewController.m
Blockchain/Wallet.m

Moving busy view presentation to `LoadingPresenter`. Note that this is simply a wrapper around the current way that an activity indicator is displayed to the user. This is just so that we can untangle this logic away from RootService. We'll need to come up with a better solution longer-term (sometime after RootService is fully deprecated).
Please review/merge #104 before this

refactor(LoadingPresenter): create LoadingPresenter.

---

Blockchain/BCPriceMarker.swift
Blockchain/Blockchain-Bridging-Header.h
Blockchain/DashboardViewController.m
Blockchain/NSNumberFormatter+Currencies.m

Currently `dev` returns 0 fiat balance for ETH because of comma grouping separators. This branch fixes that and adds grouping separators (e.g. thousands separator) to other fiat labels in the pie chart and legend keys. Grouping separators for crypto values should wait until a further release.

Fix eth balance

---

Blockchain/AccountsAndAddressesDetailViewController.m
Blockchain/AccountsAndAddressesNavigationController.m
Blockchain/BCAddressSelectionView.m
Blockchain/BCFadeView.h
Blockchain/BCNavigationController.m
Blockchain/BuyBitcoinViewController.m
Blockchain/ContactDetailViewController.m
Blockchain/ContactTransactionTableViewCell.m
Blockchain/ContactsViewController.m
Blockchain/RootService.h
Blockchain/RootService.m
Blockchain/SendBitcoinViewController.m
Blockchain/SettingsNavigationController.m
Blockchain/TransactionEtherTableViewCell.m
Blockchain/TransactionTableCell.m
Blockchain/TransactionsBitcoinViewController.m
Blockchain/UpgradeViewController.m

Deprecate `topViewControllerDelegate` in RootService. This field can now be obtained through:
```
UIApplication.shared.keyWindow.rootViewController.topMostViewController
```
If you need to check if it is of type `TopViewController`, just check the type of that field.
Longer-term note: this is again a work-around with the current approach of how `UIViewController`s are presented in the app. It's much better to present a `UIViewController` from the instance that needs to present it. This can be tied in to the coordinator pattern, too.
Please review/merge #106 before reviewing this.

 refactor(TopViewController): deprecate topViewControllerDelegate.

---

Blockchain.xcodeproj/project.pbxproj
Blockchain/AppDelegate.swift
Blockchain/Blockchain-Prefix.pch
Blockchain/Constants.swift
Blockchain/Extensions/UIDevice.swift
Blockchain/Notifications/PushNotificationManager.swift
Blockchain/RootService.h
Blockchain/RootService.m
Blockchain/Wallet/WalletManager.swift

Created `PushNotificationManager` which manages everything related to push notifications (i.e. encapsulates the method for requesting for push permission and it sets itself as a `UNUserNotificationDelegate`).
Please review #109 first
----
**Feedback need for the following:** This PR also contains a `WalletManager` object which contains the `Wallet` instance (currently in `RootService`). It also sets itself as the `WalletDelegate` to that instance. Having wallet in `RootService` is currently blocking further refactoring of `RootService` as wallet is referenced in many different places—moving it to `WalletManager` will unblock that. 
Once we get started on an asset-based wallet architecture, we can then remove that instance from `WalletManager`. But, I do think it will remain to be a …

refactor(PushNotificationManager): creating PushNotificationManager.

---

Blockchain/AppDelegate.swift
Blockchain/Coordinators/AppCoordinator.swift
Blockchain/Settings/BlockchainSettings.swift
Blockchain/Wallet/WalletManager.swift

So that the application-level never has to interface with the keychain.
Also, should we put other properties that are currently in `BlockchainSettings.App` in here (e.g. `passwordPartHash`)?

refactor(BlockchainSettings): moving guid and sharedKey to BlockchainSettings.Wallet

---

Blockchain.xcodeproj/project.pbxproj
Blockchain/AppDelegate.swift
Blockchain/Assets/AssetAddress.swift
Blockchain/Assets/Bitcoin/BitcoinAddress.swift
Blockchain/Assets/BitcoinCash/BitcoinCashAddress.swift
Blockchain/Blockchain-Prefix.pch
Blockchain/Network/Extensions/BlockchainAPI+URLSuffix.swift
Blockchain/Network/NetworkManager.swift
Blockchain/RootService.m
BlockchainTests/BlockchainAPI+URLSuffixTests.swift
BlockchainTests/CheckForUnusedAddressTests.swift
BlockchainTests/Mock Data/sample-unused-address.json

This PR migrates `checkForUnusedAddress` to Swift using the new `AssetAddress` type.
TODO: move `checkForUnusedAddress` to a more appropriate place than the application delegate.

Asset address

---

Blockchain.xcodeproj/project.pbxproj
Blockchain/Alerts/AlertViewPresenter.swift
Blockchain/AppDelegate.swift
Blockchain/AuthenticationCoordinator.swift
Blockchain/Blockchain-Bridging-Header.h
Blockchain/Blockchain-Prefix.pch
Blockchain/Constants.swift
Blockchain/Extensions/UIApplication.swift
Blockchain/LocalizationConstants.h
Blockchain/LocalizationConstants.swift
Blockchain/Pin/Pin.swift
Blockchain/ReminderModalViewController.h
Blockchain/ReminderModalViewController.m
Blockchain/RootService.h
Blockchain/RootService.m
Blockchain/Settings/BlockchainSettings.swift
Blockchain/SettingsAboutUsViewController.m
Blockchain/Wallet/WalletManager.swift
Blockchain/WalletSetupViewController.h
Blockchain/WalletSetupViewController.m
BlockchainTests/PinTests.swift
PinEntry/Classes/PEPinEntryController.m

Summary:
* Created `AuthenticationCoordinator` and move `PEPinEntryViewController` flow in here
* Migrated `PEPinEntryViewController` pin delegate methods in `AuthenticationCoordinator`
* Created `Pin` class
Note: pin entry flow has not yet been fully migrated (i.e. pin-related wallet delegate calls, touch ID, etc.). Will work on that in a separate PR.

refactor(AuthenticationCoordinator): Move pin entry flow to AuthenticationCoordinator.

---

Blockchain.xcodeproj/project.pbxproj
Blockchain/Alerts/AlertViewPresenter.swift
Blockchain/Authentication/AuthenticationCoordinator.swift
Blockchain/Authentication/AuthenticationManager.swift
Blockchain/Authentication/Models/AuthenticationCoordinator+Pin.swift
Blockchain/Authentication/Models/AuthenticationError.swift
Blockchain/BCCreateWalletView.m
Blockchain/Blockchain-Prefix.pch
Blockchain/Constants.swift
Blockchain/Extensions/Strings.swift
Blockchain/LocalizationConstants.h
Blockchain/LocalizationConstants.swift
Blockchain/Pin/Pin.swift
Blockchain/RootService.h
Blockchain/RootService.m
Blockchain/Wallet.m
Blockchain/Wallet/Models/GetPinResponse.swift
Blockchain/Wallet/Models/PutPinResponse.swift
Blockchain/Wallet/WalletAuthDelegate.swift
Blockchain/Wallet/WalletManager.swift
Blockchain/Wallet/WalletPinEntryDelegate.swift
PinEntry/Classes/PEPinEntryController.m

* Moved pin creation from RootService to AuthenticationCoordinator
* Created `GetPinResponse` & `PutPinResponse` model objects to wrap pin-related API responses
* Created `WalletPinEntryDelegate` to wrap `WalletDelegate` pin-related methods
Please review/merge PRs all PRs < #132 before reviewing this

refactor(pin): Complete pin entry flow on new wallet creation.

---

Blockchain/Alerts/AlertViewPresenter.swift
Blockchain/Authentication/AuthenticationCoordinator.swift
Blockchain/Authentication/Models/AuthenticationCoordinator+Pin.swift
Blockchain/Extensions/UIApplication.swift

This PR adds support for custom alert actions for the `standardNotify` functions. It also fixes an issue that prevented alerts from showing while the application was transitioning to the active state.

feat(Alert View Presenter): support custom alert actions

---

Blockchain.xcodeproj/project.pbxproj
Blockchain/AccountsAndAddressesDetailViewController.m
Blockchain/AppDelegate.swift
Blockchain/Authentication/AuthenticationCoordinator.swift
Blockchain/Authentication/Models/PostAuthenticationRoute.swift
Blockchain/Notifications/PushNotificationManager.swift
Blockchain/QRCodeScannerSendViewController.m
Blockchain/RootService.h
Blockchain/RootService.m

* Moved `showType` away from `RootService` and renamed this enum to `PostAuthenticationRoute`.
* Added back `userNotificationCenter:didReceive:withCompletionHandler` back to `PushNotificationManager` since it was accidentally removed on b79a4b35 (@woudini can you confirm that `ShowTypeNewPayment` was actually used and not part of contacts in which case we should remove it?)
* Commented out some more unused code in `RootService`

refactor(ShowType): Migrating show type to PostAuthenticationRoute.

---

Blockchain.xcodeproj/project.pbxproj
Blockchain/AccountsAndAddressesDetailViewController.m
Blockchain/AccountsAndAddressesNavigationController.m
Blockchain/Authentication/AuthenticationCoordinator+Biometrics.swift
Blockchain/Authentication/AuthenticationCoordinator.swift
Blockchain/Authentication/Models/AuthenticationCoordinator+Pin.swift
Blockchain/Blockchain-Prefix.pch
Blockchain/Feature Configuration/AppFeature.swift
Blockchain/Feature Configuration/AppFeatureConfiguration.swift
Blockchain/Feature Configuration/AppFeatureConfigurator.swift
Blockchain/Pin/Pin.swift
Blockchain/SettingsTableViewController.m
PinEntry/Classes/PEPinEntryController.m

Removing `#defines`  for enabling/disabling app features such as touch ID, swipe to receive, etc. If a component requires a configuration for a specific feature, it will request it by invoking `AppFeatureConfigurator.shared.configuration(for: feature)`. The benefit of using a design like this is that we can eventually add more specific feature configurations into an instance of `AppFeatureConfiguration`. At the moment, all it does is tell you if a feature is enabled or not (by default, all features are enabled).
Other changes:
* Renamed extension class to `AuthenticationCoordinator+Biometrics`
* Implemented TODOs that depended on the `#define ENABLE_TOUCH_ID`
* Removed #defines

refactor(AppFeature): Removing #defines for app feature enabling.

---

Blockchain/Authentication/Models/AuthenticationCoordinator+Pin.swift
Blockchain/LocalizationConstants.swift
Blockchain/RootService.h
Blockchain/RootService.m
Blockchain/SettingsTableViewController.m

Also fixed swiftlint error about having deeply nested classes (i.e. `LocalizationConstants.Authentication.Pin`). The linter recommends only one level of nesting.

refactor(pin): migrate change pin out of RootService

---

Blockchain/AppDelegate.swift
Blockchain/Coordinators/AppCoordinator.swift
Blockchain/ExchangeTableViewCell.m
Blockchain/RootService.h
Blockchain/RootService.m
Blockchain/Settings/BlockchainSettings.swift
Blockchain/SideMenuViewController.m
Blockchain/TransactionDetailViewController.m
Blockchain/TransactionsBitcoinViewController.m

Can't test this until `app->symbolLocal` is migrated.
@woudini, I won't mess with that since you mentioned you're changing that.

refactor(filter): remove asset filtering from RootService.

---

Blockchain.xcodeproj/project.pbxproj
Blockchain/BCAddressSelectionView.m
Blockchain/BCCreateWalletView.m
Blockchain/Blockchain-Bridging-Header.h
Blockchain/Blockchain-Prefix.pch
Blockchain/Coordinators/AppCoordinator.swift
Blockchain/ExchangeTableViewCell.m
Blockchain/Extensions/UserDefaults.swift
Blockchain/NSNumberFormatter+Currencies.m
Blockchain/RootService.m
Blockchain/SendBitcoinViewController.m
Blockchain/SendEtherViewController.m
Blockchain/Settings/BlockchainSettings.swift
Blockchain/SettingsSelectorTableViewController.h
Blockchain/SettingsTableViewController.m
Blockchain/TabControllerManager.m
Blockchain/TransactionEtherTableViewCell.m
Blockchain/TransactionsBitcoinViewController.m
Blockchain/TransactionsEtherViewController.m
Blockchain/Wallet.h
Blockchain/Wallet.m
Blockchain/Wallet/WalletAccountInfoAndExchangeRatesDelegate.swift
Blockchain/Wallet/WalletManager.swift
Blockchain/js/wallet-ios.js

Clean up the flow of methods on startup, which was previously the following:
```
Multiaddr
did_multiaddr
didGetMultiAddressResponse
getAccountInfo
reloadAfterGettingCurrencySymbols -> updateSymbols (BTC rates)
fetchBitcoinCashExchangeRates
getEthExchangeRate
```

refactor(RootService): clean up API calls on startup

---

Blockchain.xcodeproj/project.pbxproj
Blockchain/AccountsAndAddressesNavigationController.m
Blockchain/BCBalancesChartView.m
Blockchain/BackupViewController.swift
Blockchain/Blockchain-Bridging-Header.h
Blockchain/Blockchain-Prefix.pch
Blockchain/Constants.swift
Blockchain/Coordinators/AppCoordinator.swift
Blockchain/Coordinators/TransferAllCoordinator.swift
Blockchain/DestinationAddressSource.h
Blockchain/EtherAmountInputViewController.h
Blockchain/EtherAmountInputViewController.m
Blockchain/NSNumberFormatter+Currencies.m
Blockchain/RootService.h
Blockchain/RootService.m
Blockchain/SendBitcoinViewController.h
Blockchain/SendEtherViewController.h
Blockchain/SendEtherViewController.m
Blockchain/TabControllerManager.h
Blockchain/TabControllerManager.m
Blockchain/TransferAllFundsBuilder.m
Blockchain/Wallet.h
Blockchain/Wallet/WalletExchangeIntermediateDelegate.swift
Blockchain/Wallet/WalletManager.swift
Blockchain/Wallet/WalletTransactionDelegate.swift
Blockchain/Wallet/WalletTransferAllDelegate.swift

Some other changes:
- Re-implemented `reloadAfterMultiAddressResponse` inside `AppCoordinator`
- If `symbol_local` is nil, changed to return nil for local currency conversion. This seems to be happening due to `backup_wallet_success` calling `reload` before `getAccountInfoAndExchangeRates` has a chance to set `symbol_local` after `latestMultiAddressResponse` has been reset. If possible we should store `symbol_local` separately from `latestMultiAddressResponse`.
- Created `DestinationAddressSource.h` and added to `SendEtherViewController`. Tried making a swift enum multiple times (added to both main and test target) and the compiler couldn't find `Blockchain-Swift.h`

refactor(RootService): set app coordinator as transfer all delegate

---

Blockchain.xcodeproj/project.pbxproj
Blockchain/AccountsAndAddressesNavigationController.m
Blockchain/Addresses/AssetAddressRepository.swift
Blockchain/AppDelegate.swift
Blockchain/Assets/AssetType.swift
Blockchain/RootService.m
Blockchain/SettingsTableViewController.m
Blockchain/Wallet/WalletManager.swift
Blockchain/Wallet/WalletSwipeAddressDelegate.swift
PinEntry/Classes/PEPinEntryController.m

* Migrated out `didGetSwipeAddresses` from `RootService`.
* Created `AssetAddressRepository` component for retrieving addresses—would like to move latestMultiAddress response (currently in WalletManager) in there as well.
* Removed all direct references to the KeychainItemWrapper and instead reference the new `AssetAddressRepository`

refactor(swipe): creating AssetAddressRepository and WalletSwipeAddressDelegate.

---

Blockchain/Coordinators/KeyImportCoordinator.swift
Blockchain/LocalizationConstants.h
Blockchain/LocalizationConstants.swift
Blockchain/RootService.m
Blockchain/Wallet.h
Blockchain/Wallet.m
Blockchain/Wallet/WalletKeyImportDelegate.swift

This PR migrates `alertUserOfInvalidPrivateKey` from `RootService` to `WalletKeyImportDelegate`.

Migrate alertUserOfInvalidPrivateKey

---

Blockchain/Authentication/AuthenticationCoordinator.swift

Bug was because `topMostViewController` is non-deterministic—sometimes it was `ECSlidingViewController`, other times it was `PairingCodeParser`. Fix is to always use `rootViewController`.

fix(pairing): ask to set pin after pairing.

---

Blockchain/TabControllerManager.m

The order of the LegacyAssetType enum (BTC, BCH, ETH) being different from the original (BTC, ETH, BCH) was causing the fiat at time to fail because of conflicting parameter types. Can we change that?

fix(FiatAtTime): fix conflicting parameter types

---

Blockchain/AppDelegate.swift
Blockchain/BCFadeView.m
Blockchain/Coordinators/AppCoordinator.swift
Blockchain/LoadingViewPresenter.swift
Blockchain/ModalPresenter.swift
Blockchain/TabControllerManager.m

* Adding busyView at the top-most window level. This way, no matter what views/view controllers are presented under, the loading view will always be displayed
* Making busyView `private`. We used to leak this state to external components to check if there is a loading view presented. Now, we can check if a loading view is displayed by querying `LoadingViewPresenter.shared.isLoadingShown`

fix(loading): make loading view visible over all views.

---

Blockchain/UIViewController.swift

`PasswordRequiredView` sometimes gets presented in a cut-off way. This change fixes that.

fix(modal): prevent modal presentation on UIAlertViewController

---

Blockchain/Authentication/AuthenticationCoordinator.swift
Blockchain/Authentication/Models/AuthenticationCoordinator+Pin.swift
Blockchain/LoadingViewPresenter.swift
Blockchain/ModalPresenter.swift
Blockchain/TabControllerManager.h
Blockchain/TabControllerManager.m
Blockchain/Wallet.m
Blockchain/Wallet/WalletManager.swift
Blockchain/js/wallet-ios.js

The loading/busy view was not being presented in some areas (manual pairing, password required view, etc.) because the action was dispatched asynchronously to the GCD. So, if that queue is congested (like in the case of password auth since it does), the loading view may not be presented. This change fixes that issue by guaranteeing that an invocation to one of the `LoadingViewPresenter` methods execute on the main thread (previous was async and passed to the main queue).
As I brought up before, we want wallet delegate methods to always be invoked on the main thread (removes all the guesswork whether or not a callback is executed on the main or background thread). I went ahead and guaranteed that by calling the wallet delegate methods from within a block dispatched to GCD on the main …

fix(loading): Loading presentation

---

Blockchain/Authentication/AuthenticationCoordinator.swift
Blockchain/Authentication/Models/AuthenticationCoordinator+Pin.swift

Fixes the bug where a timeout alert was being presented when you enter an incorrect pin and wait for 30 seconds.

fix(login): invalidate timeout on authentication success and failure.

---

Blockchain/Coordinators/OnboardingCoordinator.swift

Used to always display "Create New Wallet" when going through the recover funds flow.

fix(recover): display 'Recover Funds' header title.

---

Blockchain/String+EscapeJS.swift
BlockchainTests/String+EscapeJSTests.swift

Bug was that the double quote character was being escaped before the backlash character which resulted in an extra backslash.

fix(JS escaped string): Properly escaping double quote character.

---

Blockchain/TransactionsBitcoinViewController.m

This fixes a bug (pasted below for more context) wherein an exception is triggered if you have the transactions list open while receiving a new transaction.
```
2018-06-07 11:58:32.555182-0700 Blockchain[498:77105] *** Assertion failure in -[UITableView _endCellAnimationsWithContext:], 
/BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit/UIKit-3698.54.4/UITableView.m:2012
2018-06-07 11:58:32.572747-0700 Blockchain[498:77564] +[UncaughtExceptionHandler logException:walletIsLoaded:walletIsInitialized:] [Line 111] Logging exception: 
<pre>App Version: Blockchain, Version 2.4.6 (24)
System Name: iOS -  System Version : 11.4
Active View Controller: TransactionsBitcoinViewController
Wallet State: JSLoaded = FALSE, isInitialized = TRUE
Device:  Language: en-US
GUID Hash: …
```

fix(tx): Removing delay when animating first cell.

---

Blockchain.xcodeproj/project.pbxproj
Blockchain/Addresses/AssetAddressFactory.swift
Blockchain/Addresses/AssetAddressRepository.swift
Blockchain/Addresses/BitcoinCashAddress.swift
Blockchain/Network/Extensions/BlockchainAPI+URLSuffix.swift
Blockchain/Wallet/WalletManager.swift
BlockchainTests/Addresses/AssetAddressFactoryTests.swift
PinEntry/Classes/PEPinEntryController.m

BCH swipe address was not correctly showing because we were not transforming the BCH address to a BTC address before passing it to the `https://api.blockchain.info/bch/multiaddr` endpoint.

fix(bch): showing BCH swipe address

---

Blockchain/TransactionsBitcoinViewController.m

Fixes bug where the received tx amount would occasionally show the incorrect tx (it would show the 2nd to last one). The reason for this is because there was a race condition between when the multiaddress response and when we were displaying the alert message. Fix is to only check if the alert should be displayed after `TransactionsBitcoinViewController` receives the multiaddress response.

fix(tx): display correct tx received amount.

---

Blockchain/Authentication/AuthenticationCoordinator.swift
Blockchain/Authentication/AuthenticationManager.swift
Blockchain/BCManualPairView.m
Blockchain/LocalizationConstants.swift
Blockchain/Wallet/WalletAuthDelegate.swift

Fixes related to 2FA:
* SMS & Google Auth | fix issue where the 2FA verification dialog (sms & google auth) would not be presented if the email authentication alert is still presented
* Email Auth | update email authorization alert message to instruct the user to return to the app after they have authorized the log in attempt

fix(2fa): fix 2FA flow

---

Blockchain/TabViewController.m
Blockchain/TransactionsBitcoinViewController.m
Blockchain/TransactionsViewController.m

- Adds iPhone X support to the **Transactions Screen**.
```
iPhone X Support for Transactions Screen (#241)
```

iPhone X Support for Transactions Screen

---

Blockchain/AccountsAndAddressesDetailViewController.m
Blockchain/AccountsAndAddressesViewController.m
Blockchain/Coordinators/KeyImportCoordinator.swift
Blockchain/Extensions/UINavigationBar+TitleAttributes.swift
Blockchain/PrivateKeyReader/PrivateKeyReader.swift
Blockchain/SendBitcoinViewController.m

Fixes 2 issues:
* bug wherein the QR code scanner was not being presented when tapping on "Scan Private Key"
* bug wherein the scanned private key was displaying the alert "Your wallet does not contain this address." even though the address is in your wallet
Tested this by creating a wallet on https://www.bitaddress.org/

fix(PrivateKeyReader): fix errors when trying to scan private key.

---

Blockchain/BCNavigationController.m
Blockchain/SettingsWebViewController.m

Adding iPhone X support for the "Log in to Web Wallet" screen. 
This involved having to modify the frame and positioning of views within `BCNavigationController` which is used by other view controllers. As a result, this change also affected the following views:
* TOS, PP & Cookies Policy web views

iPhone X support for Web Login View

---

Blockchain/ReceiveBitcoinViewController.m

The UIView containing the QR code + address was blocking the input fields.
Tested this on iPhone X and iPhone 5S and verified that those input fields are now tappable.

fix(RequestBitcoinViewController): make UITextFields tappable on iPhone X

---

Blockchain/TabViewController.m

Tested on iPhone 5S and manually set the title to be a really large balance e.g. "$50,333,456.00" and verified that it renders correctly.

fix(TabViewController): prevent navigation header from cutting off for large balances.

---

Blockchain/BCConfirmPaymentView.h
Blockchain/BCConfirmPaymentView.m
Blockchain/SendBitcoinViewController.m
Blockchain/SendEtherViewController.m

- Fixes the out of view confirm button on the send confirmation screen.
- Removes old contacts-related method.

fix(Send Screen): make confirm button visible on iPhone X

---

Blockchain/AccountsAndAddressesDetailViewController.m
Blockchain/Base.lproj/AccountsAndAddresses.storyboard

- Shows the missing titles in the edit views of the Accounts and Addresses screen.

fix(Accounts+Addresses): show navigation item title in edit views

---

Blockchain/ExchangeOverviewViewController.m
Blockchain/Wallet/WalletExchangeDelegate.swift
Blockchain/Wallet/WalletManager.swift

- Fixes a crash where the user creates a new exchange with no free outputs to spend.

fix(Exchange): prevent app crash when exchange is created

---

Blockchain.xcodeproj/project.pbxproj
Blockchain/Addresses/BitcoinAddress.swift
Blockchain/TransactionDetailViewController.m
Blockchain/TransactionDetailViewModel.m
Blockchain/Wallet.m
BlockchainTests/Addresses/BitcoinAddressTests.swift

Fixed regression caused by removing ":" from our asset prefix constants.
I added a transformation function in `BitcoinAddress` to transform it to a `BitcoinCashAddress` + a unit test to check that the transformed bch address does not have a ":".

fix(Bitcoin Cash TX): Prevent ':' being prefixed from BCH TX detail screen

---

PinEntry/Classes/PEPinEntryController.m

Fixing the issue wherein the swipe to receive addresses do not show upon foregrounding the app right after creating a new wallet or automatically pairing an existing wallet.
Although this fix addresses that issue, note that this isn't the _ideal_ fix. The reason we need to move updating the swipe to receive views in `viewWillLayoutSubviews` (instead of `viewWillAppear`) is that the pin view may also be added "modally" (i.e. it will be added as a subview to the top most view in the view hierarchy). This is really bad and instead should use the standard way of presenting a `UIViewController` (I'm fixing that issue in #238 but is a larger change that I'm still testing).
Tested this and verified that the addresses on the swipe to receive views show up.

fix(Swipe to Receive): update swipe to receive addresses when foregrounding app

---

Blockchain/js/wallet-ios.js

Previously when entering an invalid email, no such error would be presented to the user. 
Tested this change by entering the email "test@doesnotexist.", and valid passwords, and verified that I saw the alert.

fix(Create Wallet): displaying error message when entering an invalid email.

---

Blockchain/Extensions/Enum+RawValued.swift
Blockchain/Feature Configuration/AppFeature.swift
Blockchain/Feature Configuration/AppFeatureConfigurator.swift

Fixes crash on release builds when trying to first access `AppFeature`. 
Unclear why this is happening only on release builds but the operation `AppFeature.rawValues` would eventually cause a buffer overflow and crash the app (the `AnyIterator` inside the `rawValues` implementation will continue to iterate even though no further enums with such values exist). Also, this only happens on enums that are Ints (does not happen to other enums that are Strings). I wanted to fix this on the `RawValued` implementation but could not come up with a solution.
As a fix, I've defined a static `allFeatures` property. Once Swift 4.2 is supported, we can updated that enum and conform to `CaseIterable`.

fix(RawValued): fixing crash on release builds when using RawValued int enum

---

Blockchain/ReceiveBitcoinViewController.h
Blockchain/ReceiveBitcoinViewController.m

Fixes the issue wherein the alert shown when a payment is received displays duplicate payment amounts in BTC.
Ideally the fiat amount right after the BTC amount should be displayed (which happens most of the time). However, there is a race condition wherein we don't have the user's local currency's conversion value from/to BTC amount. When this happens, we'll just display the BTC amount and leave the fiat amount off. Also weird, when the local currency conversion is not available, the `NSNumberFormatter:formatMoney:localCurrency` method will fallback to _always_ just convert the amount to BTC and completely ignore the `localCurrency` flag. Fixing this method may have some unintended consequences since it's used in a lot of other places so I figured this patch will do for now.
Obviously …

fix(Receive): prevent BTC payment received amount from showing twice.

---

Blockchain/BackupVerifyViewController.swift
Blockchain/BackupWordsViewController.swift
Blockchain/Base.lproj/Backup.storyboard
Blockchain/SecondPasswordViewController.swift

- Adds iPhone X support to the **Second Password** screen.
- Replaces the fake navigation bar with a real UINavigationBar.
- Adds Autolayout support for Second Password screen.

feat(Second Password): add iPhone X support

---

Blockchain/Base.lproj/SendCoins.xib
Blockchain/DestinationAddressSource.h
Blockchain/ReceiveBitcoinViewController.m
Blockchain/SendBitcoinViewController.h
Blockchain/SendBitcoinViewController.m
Blockchain/SendEtherViewController.m
Blockchain/TabControllerManager.m

- In the **Send** and **Request** views, amount fields are now cleared when navigating away from them.
- The **Send** view also resets the **To** field and the **Use total available minus fee** label.
- Removed more references to the deprecated **Contacts** feature.

fix(Send): clear amount fields when view disappears

---

Blockchain/Addresses/AddressValidator.swift
Blockchain/LocalizationConstants.h
Blockchain/LocalizationConstants.swift
Blockchain/SendBitcoinViewController.m
Blockchain/URL/AssetURLPayload.swift
Blockchain/URL/AssetURLPayloadFactory.swift
Blockchain/URL/BitcoinCashURLPayload.swift
Blockchain/URL/BitcoinURLPayload.swift
BlockchainTests/AddressValidatorTests.swift
BlockchainTests/URL/AssetURLPayloadFactoryTests.swift

Tested all the following cases:
BITCOIN:
* Should accept BTC address with prefix bitcoin:1K43HTP8ayuJjfqAHG7azwVDDQaDwLtqtK
* Should accept BTC address without prefix 1K43HTP8ayuJjfqAHG7azwVDDQaDwLtqtK
* Should not accept addresses with other currency prefix or address
BITCOIN CASH:
* Should accept BCH address with prefix bitcoincash:qpheqxjud2p0yg85t679tnc7n05xffs5ks07zhg6y6
* Should accept BCH address without prefix qpheqxjud2p0yg85t679tnc7n05xffs5ks07zhg6y6
* Should accept BCH legacy address with prefix bitcoincash:1K43HTP8ayuJjfqAHG7azwVDDQaDwLtqtK
* Should accept BCH legacy address without prefix 1K43HTP8ayuJjfqAHG7azwVDDQaDwLtqtK
* Should not accept addresses with other currency prefix
ETHER:
* Should accept ETH address without prefix 0x6584EF6C986d82d9B48683312cFb66234896bF2c
* …

fix(send): correctly handle different permutations of QR code addresses for all assets.

---

PinEntry/Classes/PEViewController.m

Fixes the issue wherein the keyboard view was stretched on the iPhone X.
Screenshots:
**iPhone X:**
**iPhone 6S:**
**iPhone 5S:**

fix(Pin): fix aspect ratio of pin entry keyboard to 19:16.

---

Blockchain/Coordinators/AppCoordinator.swift

Fixes issue where the upgrade prompt was not being presented open authenticating into a legacy wallet. The reason it wasn't shown was because the UpgradeViewController was being presented from a UIViewController that was not in the view hierarchy (i.e. from the PEViewController). Fix is to always present from the rootViewController.

fix(UpgradeViewController): always present HD upgrade screen when authenticating with a legacy wallet

---

Blockchain/AppDelegate.swift
Blockchain/Authentication/AuthenticationCoordinator.swift
Blockchain/Authentication/Models/AuthenticationCoordinator+Pin.swift
Blockchain/Extensions/UserDefaults.swift
Blockchain/Feature Configuration/AppFeature.swift
Blockchain/LocalizationConstants.h
Blockchain/LocalizationConstants.swift
Blockchain/Pin/Pin.swift
Blockchain/Reminder/ReminderPresenter.swift
Blockchain/Settings/BlockchainSettings.swift
Blockchain/SettingsTableViewController.m
Blockchain/Wallet/WalletManager.swift
Blockchain/WalletSetupViewController.m

- Now shows the correct biometric authentication type in the **Settings** view.
- Now shows the correct biometric authentication type in the **Wallet Setup** view.
- Standardizes the naming of objects related to biometric authentication (to be more agnostic).
- Correctly sizes header labels for table view sections.
Two keys in the UserDefaults have been renamed to reflect the object name standardization and thus will **disable** biometric authentication the **first time** the user returns to the app after updating the application.
Some localized constants were also affected and thus translations need to be updated before merging this PR.
As mentioned in the code docs, we should not have a toggle to opt-in to using biometric authentication, but rather prompt the user …

fix(Settings): show correct biometric type in settings

---

Blockchain/SendEtherViewController.m

Send ETH used to show all 18 decimal places. This PR fixes that by truncating the ETH amount to 8 decimal places.

fix(Send ETH): truncate ETH to 8 decimal places.

---

Blockchain/js/wallet-ios.js

Fixes the issue where received funds always goes to the 1st BCH address. 
Tested that this works and verified that funds were always received to the correct address (the default address).

fix(Swipe to Receive): make sure swipe to receive BCH funds goes to default address

---

Blockchain/SendBitcoinViewController.m

Assignment of dust property:
- A property named `dust` is used to locally store the dust value for the frontend to use.
- The dust threshold `[app.wallet dust]` was called for when a contact transaction (deprecated feature) was to be created.
- When adding BCH, a method `-(uint64_t)dust` was added to replace `[app.wallet dust]` so that it could branch cleanly with an if statement depending on whether BTC or BCH was used.
- This change inadvertently started returning the dust threshold when `self.dust` was read. As a result, incorrect dust amounts were displayed.
- This issue could have been avoided if I had better named `Wallet.h`'s `dust` as `dustThreshold`.
Fee amount calculation:
- Origin: https://github.com/blockchain/My-Wallet-V3-iOS/commit/732ed311060d315d9ef89b77e428a5b8dcc501d5#dif …

Fix assignment of dust property and fee amount

---

Blockchain/BCModalView.h
Blockchain/BCModalView.m

- Prevents the header label in the fake navigation bar from overlapping with its neighboring fake bar button items.
Note:
BCModalView should be deprecated soon.

fix(BCModalView): prevent header label overlap

---

Blockchain/AppDelegate.swift
Blockchain/Authentication/AuthenticationCoordinator.swift
Blockchain/BCCreateWalletView.m
Blockchain/BCManualPairView.m
Blockchain/Blockchain-Prefix.pch
Blockchain/CardsViewController.m
Blockchain/Extensions/UserDefaults.swift
Blockchain/Settings/BlockchainSettings.swift
Blockchain/Wallet.m

The flag `hasSeenAllCards` was incorrectly being toggled to be set to `true` even though the user hasn't seen those cards upon creating a new wallet. This can happen if either the app is terminated or if the user backgrounds the app, and re-foregrounds it. 
With this PR, the only way to dismiss these cards now is to either view all of them, or by tapping on "Skip All".
**Summary of changes**:
* remove areas in the code wherein `hasSeenAllCards` should not be set to _true_
* remove redundant flag `shouldHideAllCards`
Tested this by creating a new wallet, background/foreground app, and verified that the onboarding cards are still shown.

 fix(Onboarding Cards): guarantee that onboarding cards are shown when creating a new wallet

---

Blockchain/Alerts/AlertViewPresenter.swift

Issue was because an alert was trying to be presented from ECSlidingViewController which was not the top most view controller (there was another view controller presented on top of it).
With this change, I tested that alerts were being presented when tapping on "Import Addresses" from the addresses view. Also tested a bunch of other scenarios in that app where an alert should be presented and verified that it did.

fix(Alerts): fix issue where alerts are sometimes not presented.

---

Blockchain/BCAddressSelectionView.m
Blockchain/BCConfirmPaymentView.m
Blockchain/BCConfirmPaymentViewModel.h
Blockchain/BCConfirmPaymentViewModel.m
Blockchain/LocalizationConstants.h
Blockchain/LocalizationConstants.swift
Blockchain/SendEtherViewController.m

- Shows the missing fields on the ethereum payment confirmation screen.
Tested with different local currency symbols to ensure it works.

 fix(Send): show missing fields on confirmation screen

---

Blockchain/TabControllerManager.m

Looks like it wasn't being presented because of the change wherein the alert was trying to be presented from `TabControllerManager` which is not in the foreground. Setting the "in:" parameter to `nil` will use the `topMostViewController` so that the alert is presented correctly.
These are the sort of side-effects that having a single delegate on the `Wallet` create. Once we get to refactoring websockets out of the `Wallet`, we'll have a more robust solution.

fix(Payment Received): fix payment received alert not shown on pin screen

---

Blockchain/TabControllerManager.m

Fixes the issue wherein the QR scanner would not be presented when tapping on 'Scan Address' from the onboarding card. The fix was to set the active tab first before calling the method `QRCodebuttonClicked`.

fix(Scan Address): show QR scanner when tapping on 'Scan Address' from onboarding card.

---

Blockchain/AccountsAndAddressesViewController.m
Blockchain/Coordinators/KeyImportCoordinator.swift
Blockchain/LocalizationConstants.swift
Blockchain/PrivateKeyReader/PrivateKeyReader.swift
Blockchain/SendBitcoinViewController.m

Issue:
unable to send from watch-only address - after scanning a private key, nothing happens, and infinite spinner results.
Stack:
`KeyImportCoordinator` presents view controller to scan private key -> `SendBitcoinViewController`'s `viewDidDisappear` -> `reload` -> `self.fromAddress = @""`
Notes:
This will reopen the bug that the `reload` in `SendBitcoinViewController`'s `viewDidDisappear` was intended to fix, which was clearing the fields when navigating away from them (reminder: do not link the tickets on github).
My suggestion is to avoid trying to clear the fields until further wallet refactoring since it could create mismatching states between the UI and payment object.
Requesting feedback on moving the import error alert presentation to the `PrivateKeyReader` - I feel like it does …

fix(Send, PrivateKeyReader): remove reload and show import error alerts

---

Blockchain/Authentication/AuthenticationCoordinator.swift
Blockchain/Authentication/Models/AuthenticationCoordinator+Pin.swift

Fixes the issue wherein when the user is prompted to enter their password after incorrectly entering their pin 4 times, they aren't asked to create a new pin.

fix(Pin): make sure user is prompted to create new pin upon entering password

---

PinEntry/Classes/PEPinEntryController.m

Fixes the issue wherein the circles in the pin entry view sometimes don't get cleared when an alert is presented.

fix(Pin): Make sure pin input is properly reseted when an alert is presented

---

Blockchain/ExchangeCreateViewController.m

Fixes the issue wherein tapping on 'Use minimum' or 'Use maximum' does not allow the user to continue until they tap on a UITextField.
With this change, if the user taps on those buttons and the keyboard isn't presented, the topLeftField will become the first responder so that the keyboard is presented.

fix(Exchange): show continue button when selecting 'use minimum/maximum'

---

Blockchain/AppDelegate.swift
Blockchain/AppReviewPrompt/AppReviewPrompt.swift
Blockchain/Extensions/UserDefaults.swift
Blockchain/SendBitcoinViewController.m
Blockchain/Settings/BlockchainSettings.swift

- Fixes an issue where the app review prompt would not show during the user's first session if the user has not had at least 3 transactions in total. The prompt will now show after the third total payment has been sent, regardless of how many times the application has been opened.

fix(App Review): show prompt on third completed transaction regardless of how often the application has become active

---

Blockchain.xcodeproj/project.pbxproj
Blockchain/Authentication/AuthenticationCoordinator.swift
Blockchain/Authentication/Models/AuthenticationCoordinator+Pin.swift
Blockchain/Coordinators/AppCoordinator.swift
Blockchain/TabControllerManager.m
Blockchain/UpgradeViewController.m
Blockchain/Wallet.h
Blockchain/Wallet.m
Blockchain/Wallet/WalletManager.swift
Blockchain/Wallet/WalletUpgradeDelegate.swift

Fix the issue wherein v2 wallets aren't forced to be upgraded if they have a 2nd password set.
This fix includes the following changes:
* The logic to present `UpgradeViewController` was moved to `TabControllerManager` (we had that in multiple places previously but now it's just in one place)
* Created `WalletUpgradeDelegate` so that upgrade success notification can be propagated up from the `Wallet`
* Not dismissing `UpgradeViewController` when the user taps on "Continue". This is necessary since previously the 2nd password view was being presented from `UpgradeViewController` which didn't show since that view controller was being dismissed
...with this change the "Upgrade" side menu item is not even necessary since this will always force the user to upgrade.
Tested this change on both …

fix(Upgrade): handle wallet upgrade for v2 wallets with a 2nd password.

---

Blockchain/BCAddressSelectionView.m
Blockchain/DashboardViewController.m
Blockchain/Wallet.h
Blockchain/Wallet.m
Blockchain/js/wallet-ios.js

Issue: when logging in with a v2 wallet, the balance in the dashboard pie chart is displaying a large negative number due to an unset double (reference https://github.com/blockchain/My-Wallet-V3-iOS/pull/327#pullrequestreview-136744354).
Fix: Removed redundant function `bitcoinCashTotalBalance` and replaced with existing function `getBchBalance` which checks for a BCH account before attempting to return the balance.

fix(Wallet): check for BCH wallet object before returning balance

---

Blockchain/Network/API/WalletService.swift
Blockchain/Network/NetworkManager.swift
BlockchainTests/Mock/MockNetworkManager.swift

Returning a Single instead of an Observable in `NetworkManager#requestJsonOrString` since only one item is emitted.
Tested this by running the app and making sure that pin validation still works and also verifying that unit tests still all pass.

refactor(NetworkManager): returning Single instead of Observable for requestJsonOrString

---

Blockchain.xcodeproj/project.pbxproj
Blockchain/Blockchain-Prefix.pch
Blockchain/ExchangeCreateViewController.h
Blockchain/ExchangeCreateViewController.m
Blockchain/ExchangeOverviewViewController.m
Blockchain/ExchangeRate.swift
Blockchain/NumberFormatter+Assets.swift
Blockchain/Wallet.h
Blockchain/Wallet.m
Blockchain/Wallet/WalletExchangeDelegate.swift
Blockchain/Wallet/WalletManager.swift
Blockchain/js/wallet-ios.js

Goal is to merge this today into `release` for a build.
**Requirement:**
If the user is in the US, enforce the upper limit from wallet options for the `from` asset type in USD. Otherwise, enforce it in EUR.
**Issue:**
BCH upper limit from wallet options was not being fetched and returned when the `from` asset type was BCH. As a result, an incorrect conversion rate was used for this limit.
The current implementation for enforcing these limits were quite messy and nonsensical:
- Regardless of the `from` asset type, both BTC and ETH hard limits were being returned to the `ExchangeCreateViewController`
- The country code check for using USD or EUR was implemented incorrectly.
- For BTC, it was getting the last fetched rate, and for ETH it was fetching the latest rate.
**Fixes**
- Fetch and …

fi(Exchange): enforce BCH upper limit from wallet options

---

Blockchain.xcodeproj/project.pbxproj

`BlockchainTests` fails to compile on `dev` because `BlockchainTests` were not added as a target for `Colors.swift`.

fix(Project): add BlockchainTests as target for Colors.swift

---

Blockchain/Views/WatchOnlyBalanceView.swift

Fixing bg color of the non-spendable label on the dashboard. Looks like the gray6 color before was different from the new gray6 color. I went ahead and searched for all other gray6 references and verified that this is the only one that was affected.
**Before:**
**After:**

fix(Dashboard): fix bg color of non-spendable label.

---

Blockchain.xcodeproj/project.pbxproj
Blockchain/AV/SoundManager.swift
Blockchain/Addresses/AssetAddressRepository.swift
Blockchain/Alerts/AlertViewPresenter+Wallet.swift
Blockchain/AppDelegate.swift
Blockchain/AppReviewPrompt/AppReviewPrompt.swift
Blockchain/Authentication/AuthenticationCoordinator+Pin.swift
Blockchain/Authentication/AuthenticationCoordinator.swift
Blockchain/Coordinators/AppCoordinator.swift
Blockchain/Coordinators/BuySellCoordinator.swift
Blockchain/Extensions/Reachability.swift
Blockchain/LoadingViewPresenter.swift
Blockchain/Logging/ConsoleLogDestination.swift
Blockchain/Logging/LogDestination.swift
Blockchain/Logging/LogLevel.swift
Blockchain/Logging/Logger.swift
Blockchain/ModalPresenter.swift
Blockchain/Models/ExchangeRate.swift
Blockchain/Models/Trade.swift
Blockchain/Network/Extensions/HTTPCookieStorage.swift
Blockchain/Network/Extensions/NetworkManager+PushNotifications.swift
Blockchain/Network/NetworkManager.swift
Blockchain/Notifications/PushNotificationManager.swift
Blockchain/Reminder/ReminderPresenter.swift
Blockchain/URL/AssetURLPayloadFactory.swift
Blockchain/Views/BCPriceMarker.swift
Blockchain/Wallet/JSContextWithDOM.swift
Blockchain/Wallet/WalletManager.swift

Created a `Logger` class for consolidating all logging into one class. Logging can now be done through using any of the following methods depending on severity: `debug()`, `info()`, `warning()`, `error()`.
Example usage:
```
Logger.shared.debug("A debug statement.")
```
The logged statement will then be displayed on the console which displays a timestamp, the file, method, and line number that invoked the log statement:
The `Logger` is also configured differently depending if the build is configured as DEBUG (i.e. no such print statements will be done on release builds).
A performance problem we have right now is that we are explicitly calling the Swift method `print()` whenever we want to print out information for debugging/error. Although the Swift compiler on occasion can optimize this …

 feat(Logger): IOS-1116 Creating Logger class.

---

.gitmodules

Adding a flag to ignore changes to git submodules. With this flag, when you do `git status`, you won't see this warning: https://cloudup.com/c0WIluR4BCL

fix(Git Submodules): Ignore changes on git submodules.

---

Blockchain.xcodeproj/project.pbxproj
Blockchain/Coordinators/AppCoordinator.swift
Blockchain/KYC/KYCCoordinator.swift
Blockchain/View Controllers/DebugTableViewController.m

* Created `KYCCoordinator` which is the new launch point for KYC
* Added a new row in `DebugTableViewController` so that KYC can be launched
* Removed commented out code in AppCoordinator for launching KYC:

feat(KYC): creating coordinator for KYC

---

Blockchain.xcodeproj/project.pbxproj
Blockchain/KYC/KYCCountrySelectionDataSource.swift
Blockchain/KYC/KYCNetworkRequest.swift
Blockchain/KYC/KYCOnboardingNavigationController.swift
Blockchain/Network/HTTPRequestError/HTTPRequestError.swift

- Addresses reusable networking code issue from #358 by adding `KYCNetworkRequest`.
- Simplifies how data is fetched in the KYC flow.
- Deprecates the use of the *delegate* pattern for making network requests.
- Restructures error handling for `KYCNetworkRequest`.
- Updates networking code for country selection screen.

refactor(KYC): make network calls reusable

---

Blockchain/Extensions/URLs.swift

Adds a simple function to `URLs.swift` to make URL endpoint generation a bit easier.
The call site would look like this:
`let parameters = ["method": "do.a.thing", "api_key": Blockchain.key]`
`guard let url = URL.endpoint(Blockchain.baseURL, pathComponents: ["path", "component"], queryParameters: parameters) else { return }`

refactor(KYC): URL convenience function

---

Blockchain.xcodeproj/project.pbxproj
Blockchain/KYC/CountrySelector/KYCCountrySelectionController.swift
Blockchain/KYC/KYCPersonalDetailsController.swift
Blockchain/KYC/Mobile Number/KYCConfirmPhoneNumberController.swift
Blockchain/KYC/Mobile Number/KYCEnterPhoneNumberController.swift
Blockchain/KYC/Storyboards/KYCConfirmPhoneNumber.storyboard
Blockchain/KYC/Storyboards/KYCEnterPhoneNumber.storyboard
Blockchain/Views/ValidationTextField/ValidationTextField.swift
Blockchain/Views/ValidationTextField/ValidationTextField.xib
Podfile

Updating the UI and improving the UX for the SMS verification flow during KYC.
Updating the UI and improving the UX for the SMS verification flow during KYC. 
UI Changes:
* added a progress view to indicate the user's progress during KYC (actual % needs to be updated and displayed)
UX Changes:
* Added PhoneNumberKit to autoformat the phone # as the user types
Other Changes:
* Added some debug code so that you can get past the country selection screen
Run the app, tap on "Debug", and tap "Launch KYC"
* Ticket Number: IOS-1052

feat(KYC): IOS-1052 Updating enter phone number screen for KYC

---

Blockchain.xcodeproj/project.pbxproj
Blockchain/Extensions/DateFormatter+Conveniences.swift
Blockchain/KYC/Address/KYCAddressController.swift
Blockchain/KYC/KYCPersonalDetailsController.swift
Blockchain/KYC/Storyboards/KYCPersonalDetails.storyboard
Blockchain/KYC/Views/ProgressableView.swift
Blockchain/Views/ValidationForm/ValidationFormView.swift
Blockchain/Views/ValidationTextField/ValidationDateField/ValidationDateField.swift
Blockchain/Views/ValidationTextField/ValidationDateField/ValidationDateField.xib
Blockchain/Views/ValidationTextField/ValidationTextField.swift
Blockchain/Views/ValidationTextField/ValidationTextField.xib

**Note:** Marking DNM due to conflict with develop and some minor polish items I'm still addressing. 
This PR includes the new `Personal Information` screen as well as a protocol for handling the `UIProgressView` that should be in all the KYC related screens. 
In addition to the features described, there's a few areas of code cleanup. 
* Added `ValidationFormView` - This protocol should be used with all `UIViewControllers` that have a `UIScrollView` and a bunch of `ValidationTextFields`. It will handle keeping the selected `UITextField` in the user's field of view when the keyboard is presented as well as checking all the fields' validation state. 
* Added `ValidationDateField` - This is only for when you have a `UITextField` that only takes a date as input. It's not ideal as I'd rather …

feat(KYC): IOS-1046 - Personal Information Screens & IOS-1141 - Progession

---

Blockchain.xcodeproj/project.pbxproj
Blockchain/KYC/Mobile Number/KYCConfirmPhoneNumberController.swift
Blockchain/KYC/Mobile Number/KYCEnterPhoneNumberController.swift
Blockchain/KYC/Storyboards/KYCConfirmPhoneNumber.storyboard
Blockchain/KYC/Views/BottomButtonContainerView.swift
Blockchain/Views/ValidationTextField/ValidationTextField.swift

Improving UX in the confirmation code view in the KYC flow.
Improving UX by:
* Using `ValidationTextField` instead of `UITextField`
* Have consistent handling of the CTA in the KYC flow (i.e. it is always enabled, however, if one of the fields are invalid, it will show an error on the `ValidationTextField` and focus)
Launch KYC and go through the different steps until entering your phone #. You won't be able to pass that step though since `userId` isn't passed around yet. To get around that, just replace line 100 in `KYCEnterPhoneNumberController`.
```
self.performSegue(withIdentifier: "verifyMobileNumber", sender: nil)
```

fix(KYC): Improve UX in KYC confirmation code view

---

Blockchain.xcodeproj/project.pbxproj
Blockchain/Constants.swift
Blockchain/Extensions/URLs.swift
Blockchain/KYC/KYCAccountStatusController.swift
Blockchain/KYC/KYCCoordinator.swift
Blockchain/KYC/Models/KYCAccountStatus.swift
Blockchain/KYC/Storyboards/KYCAccountStatus.storyboard
Blockchain/KYC/Storyboards/KYCWelcome.storyboard
Blockchain/KYC/Views/PrimaryButton.swift
Blockchain/LocalizationConstants.swift

Implementing the KYC account status view
Implemented different states for the KYC account status view. There is a function in KYCCoordinator that will handle the presentation of this view. It's currently not called anywhere but should be glued in the flow eventually (should be displayed when tapping on the item in the settings view).
Invoked `KYCCoordinator#presentAccountStatusView()` and test different account statuses.
* Ticket Number: IOS-1049

feat(KYC): IOS-1049 creating account status view.

---

Blockchain/Blockchain-Info.plist
Blockchain/KYC/KYCNetworkRequest.swift
Blockchain/Network/Extensions/BlockchainAPI+URL.swift

Moving the retail core URL to .xcconfig
All *.xcconfig files need to have `RETAIL_CORE_URL` defined.
Populate the value of `RETAIL_CORE_URL` in your *.xcconfig files and verify that the KYC flow works (probably can't really verify this yet since a lot of the endpoints don't work). 
N/A

fix(URL): move retail core URL to .xcconfig.

---

Blockchain/AppDelegate.swift
Third Party/PinEntry/Classes/PEViewController.m

The PIN entry screen was being called each time the app would resign being active, which meant that if control center or such was launched the user would have to re-enter their PIN.  This changes the lifecycle of the privacy screen to only be called when the app is moved to the background.  When the app is inactive, we apply a blur view and remove it when the app state becomes active again.
Updates lifecycle methods in the app delegate.
Video is attached.  Run the app, try launching control center and/or switching between apps and verify that the screen is blurred and unblurred when moving back to the app. Also adds haptic feedback during PIN entry.
iOS-554

fix(PIN entry): Fix pin entry screen

---

Blockchain/LocalizationConstants.h
Blockchain/LocalizationConstants.swift
Blockchain/Network/CertificatePinner.swift
Blockchain/Network/NetworkManager.swift

- Remove whitelisting of our own servers so that public key pinning can be performed
- Add back alert showing that a secure connection cannot be made
- Removed whitelisting of our own servers in the `didReceiveChallenge` `NSURLSession` delegate method.
- Implemented `didFailToValidate()` in `CertificatePinner`
See `Testing Certificate Pinning` in iOS wiki.
* Ticket Number: 1147

fix(NetworkManager): IOS-1147 only whitelist partners

---

Blockchain.xcodeproj/project.pbxproj
Blockchain/Arrays.swift
Blockchain/KYC/CountrySelector/KYCCountrySelectionController.swift
Blockchain/KYC/CountrySelector/KYCCountrySelectionPresenter.swift
Blockchain/KYC/CountrySelector/KYCCountrySelectorPresenter.swift
Blockchain/KYC/KYCNetworkRequest.swift
Blockchain/KYC/Models/KYCCountry.swift
Blockchain/KYC/Storyboards/KYCAddressController.storyboard
Blockchain/KYC/Storyboards/KYCConfirmPhoneNumberController.storyboard
Blockchain/KYC/Storyboards/KYCCountrySelectionController.storyboard
Blockchain/KYC/Storyboards/KYCEnterPhoneNumberController.storyboard
Blockchain/KYC/Storyboards/KYCPersonalDetailsController.storyboard
Blockchain/Network/API/WalletService.swift
Blockchain/Network/Models/WalletOptions.swift
BlockchainTests/KYC/KYCCountrySelectionControllerTests.swift
BlockchainTests/KYC/KYCCountrySelectionPresenterTests.swift
BlockchainTests/KYC/Mock/MockKYCCountrySelectionView.swift
BlockchainTests/Mock Data/countries.json

Polishing country selection screen.
Summary:
* Polishing country selection screen by implementing the search field, adding right hand side jump to section view
* Handling logic for what should happen when the user taps on a country and the country either is: (1) supported by our native KYC, (2) supported by Shapeshift or (3) is not supported at all.
* Added unit tests for logic mentioned above and fixed unit tests (had to add Swift files to BlockchainTests)
Note: some of this will change (i.e. `KYCCountrySelectionController` needs to be updated to integrate w/ `KYCCoordinator`) once #393 gets merged
Pull this branch and "Launch KYC" from the debug view
* Ticket Number: IOS-1045

feat(KYC): IOS-1045 Updating country selection screen

---

Blockchain/KYC/KYCAccountStatusController.swift
Blockchain/KYC/KYCCoordinator.swift
Blockchain/KYC/Models/KYCAccountStatus.swift
Blockchain/KYC/Models/KYCUser.swift
Blockchain/KYC/Personal/Models/PersonalDetails.swift

This updates `KYCUser` to reflect what is documented in the API. 
**Note: It's possible the userID will be removed entirely per internal discussion.**
* `KYCUser` now has an `id`, `state`, and `status`.
* `KYCAccountStatus` has now been updated to reflect what is documented in the API
N/A - `users` endpoint unavailable. 
N/A
* Ticket Number: N/A

fix(KYCUser): KYCUser data mapping

---

Blockchain.xcodeproj/project.pbxproj
Blockchain/Data/BlockchainDataRepository.swift
Blockchain/KYC/CountrySelector/KYCCountrySelectionController.swift
Blockchain/KYC/KYCDataRepository.swift

Creating KYCDataRepository. A component that handles fetching KYC-related models (user, countries, etc.)
`KYCDataRepository` is a component wherein layers can retrieve KYC-related data, such as the current `KYCUser`, while being agnostic as to where data is being fetched from. The 1st time a property in `KYCDataRepository` is accessed, it will be retrieved over the network followed by caching in memory. Callers are all provided a `Single<KYCData: Decodable>` type regardless if data is coming from memory or over the network.
Open to feedback if you guys think something like this is a good idea for other components to use (e.g. we can update `KYCCoordinator` to use this as well as the settings view for accessing a `KYCUser`)
Pull in these changes and launch the KYC feature. At the moment, …

feat(KYC): Creating BlockchainDataRepository.

---

Blockchain.xcodeproj/project.pbxproj

To make a directory for Homebrew, and a directory inside it for Exchange so that all Homebrew Exchange related files can be added there. Eventually the KYC directory should be moved to the Homebrew directory.
- Created a Homebrew directory
- Created an Exchange directory inside Homebrew
N/A
* Ticket Number: 1152

chore(Project): IOS-1152 add directory for homebrew and exchange

---

Blockchain/KYC/Address/KYCAddressController.swift
Blockchain/KYC/Search/API/LocationSuggestionInterface.swift
Blockchain/KYC/Search/LocationSuggestionCoordinator.swift
Blockchain/KYC/Storyboards/KYCAddressController.storyboard
Blockchain/KYC/Views/BottomButtonContainerView.swift
Blockchain/Views/ValidationForm/ValidationFormView.swift

This implements a few polish items for the address input screen.
* The `primaryButton` is always above the keyboard
* The currently in focus textField is at the top of the `UIScrollView` 
* The description labels are within the `UIScrollView`
* The `UISearchBar` is now above the `UIScrollView`
2. Go to the debug KYC flow
3. Go to the address screen. (Note: you may need to hardcode this in `screenFor(pageType:)` in the `KYCCoordinator`)
4. Use the `UISearchBar`.
5. Enter values in the fields.
6. Observe the `primaryButton`. Observe the scrolling behavior.
* Ticket Number: N/A

style(KYC): UI polish for Address input scren

---

Blockchain/KYC/KYCCoordinator.swift
Blockchain/KYC/KYCNetworkRequest.swift

Fix issue where URLSession prematurely deallocs.
Using `weak self` caused the URLSession to prematurely deinit which results in the following error:
```
Error Domain=NSURLErrorDomain Code=-999 "cancelled" UserInfo={NSErrorFailingURLStringKey=https://url.com?userId=<user_id>, NSLocalizedDescription=cancelled, NSErrorFailingURLKey=https://url.com?userId=<user_id>}
```
Updating the closure to use `unowned self` will fix this issue. With this change, you no longer need to use `URLSession.shared` in KYCNetworkRequest as I've commented before.
Launch KYC and verify that you get a valid `KYCUser`.
N/A

fix(KYC Authentication): using owned self vs. weak.

---

Blockchain.xcodeproj/project.pbxproj

Restore the ability to use the staging environment and settings.
Create a new scheme in Xcode [`Blockchain (Staging)` for example], and configure it to use the `Debug Staging` build configuration. Also make sure to enable testing by adding the `BlockchainTests` target to the `Tests` list under the scheme's Test options.

chore(Project): add staging environment scheme

---

Blockchain/Authentication/AuthenticationCoordinator.swift
Blockchain/Data/BlockchainDataRepository.swift
Blockchain/Extensions/DateFormatter+Conveniences.swift
Blockchain/KYC/KYCAuthenticationService.swift
Blockchain/KYC/KYCNetworkRequest.swift
Blockchain/KYC/Models/Network/KYCSessionTokenResponse.swift

Cache the KYC authentication session token in KYCAuthenticationService.
Previously, a new session token for authentication is requested each time when invoking `getKycSessionToken()`. With this change, we are now caching the previously fetched `KYCSessionTokenResponse` and so subsequent calls will now use that cached response. However, if the cached session token is expired, we'll fetch another one.
Writing tests for this is a bit involved—`KYCNetworkRequest` cannot be easily mocked and creating the changes to make it mock-able involves refactoring the network layer a bit. I can make that change in another PR, but since @jstxx & @achtenhagen are working on refactoring the network layer, I figured it would be good to hold off until that's in a good place (something to consider in the new …

feat(KYC Authentication): IOS-1104 caching authentication session token

---

Blockchain.xcodeproj/project.pbxproj
Blockchain/Homebrew/Exchange/ExchangeTradeCoordinator.swift
Blockchain/Homebrew/Exchange/ExchangeTradeDelegate.swift
Blockchain/Homebrew/Exchange/HomebrewExchangeCreateViewController.swift
Blockchain/Homebrew/Exchange/Views/ExchangeCreateView.swift
Blockchain/View Controllers/ExchangeCreateViewController.m
Blockchain/Views/ContinueButtonInputAccessoryView.h
Blockchain/Views/ContinueButtonInputAccessoryView.m

Use `tapped` instead of `clicked` in method names and combine protocols into `ExchangeCreateViewDelegate`.
Looking for feedback on the usage of `LegacyAssetType(rawValue: -1)!`, which is intended to mean "any asset type" so that the Address Selection View can show all asset types.
- Whitelist the dev url in `NetworkManager` (add `|| host == "dev.blockchain.com"` to `if` statement)
Homebrew:
- Replace `exchangeViewController` with `HomebrewExchangeCreateViewController` here: https://github.com/blockchain/My-Wallet-V3-iOS/blob/kevin/IOS-1159/clean_exchange/Blockchain/Coordinators/ExchangeCoordinator.swift#L104
- Add `LoadingViewPresenter.shared.hideBusyView()` here: https://github.com/blockchain/My-Wallet-V3-iOS/compare/kevin/IOS-1159/clean_exchange?expand=1#diff-ec90cea558c853745b93a95b07a8 …

refactor(Exchange): IOS-1159 rename methods and combine protocols

---

Blockchain/KYC/KYCCoordinator.swift
Blockchain/KYC/KYCWelcomeController.swift
Blockchain/KYC/Storyboards/KYCWelcomeController.storyboard

Add close button to KYC welcome screen.
Add close button to KYC welcome screen so that there is a way to exit out of KYC.
Launch KYC.
* Ticket Number: IOS-1160

feat(KYCWelcome): IOS-1160 add close button to welcome screen.

---

Blockchain/Models/ModuleXMLHttpRequest.h
Blockchain/Models/ModuleXMLHttpRequest.m

To cite the MIT license and contributor in the `ModuleXMLHttpRequest` class.

chore(ModuleXMLHttpRequest): add permission statement from MIT license

---

Blockchain/KYC/CountrySelector/KYCCountrySelectionController.swift
Blockchain/KYC/CountrySelector/KYCCountrySelectionPresenter.swift
BlockchainTests/KYC/KYCCountrySelectionPresenterTests.swift

Updating `KYCCountrySelectionPresenter` to use `WalletService.isInPartnerRegionForExchange`
Previously `KYCCountrySelectionPresenter` manually checked in `WalletOptions` if a country is supported by shapeshift of not. Since 23c92bc2 added that logic in `WalletService`, which is used by `SideMenuPresenter`, this change uses that function as well so that we are consolidating the way we determine if shapeshift is supported.
* Add the `|| host == "api.dev.blockchain.info"` in `NetworkManager` to get around the cert pinning issues
* Launch KYC and go to the country selection screen. Try selecting: (1) a homebrew supported country (e.g. Germany), (2) a SS supported country (e.g. Andorra), and (3) a SS blacklisted country (e.g. Philippines)
N/A

refactor(KYCCountrySelectionPresenter): use isInPartnerRegionForExchange

---

Blockchain.xcodeproj/project.pbxproj
Blockchain/Data/BlockchainDataRepository.swift
Blockchain/KYC/Address/KYCAddressController.swift
Blockchain/KYC/CountrySelector/KYCCountrySelectionController.swift
Blockchain/KYC/KYCAuthenticationService.swift
Blockchain/KYC/KYCBaseViewController.swift
Blockchain/KYC/KYCCoordinator.swift
Blockchain/KYC/KYCNetworkRequest.swift
Blockchain/KYC/KYCPageViewFactory.swift
Blockchain/KYC/KYCWelcomeController.swift
Blockchain/KYC/Mobile Number/KYCConfirmPhoneNumberController.swift
Blockchain/KYC/Mobile Number/KYCEnterPhoneNumberController.swift
Blockchain/KYC/Models/KYCPageError.swift
Blockchain/KYC/Models/KYCPageModel.swift
Blockchain/KYC/Models/KYCPagePayload.swift
Blockchain/KYC/Models/KYCPageType.swift
Blockchain/KYC/Models/Network/KYCUpdatePersonalDetailsRequest.swift
Blockchain/KYC/Personal/API/PersonalDetailsAPI.swift
Blockchain/KYC/Personal/KYCPersonalDetailsController.swift
Blockchain/KYC/Personal/PersonalDetailsCoordinator.swift
Blockchain/KYC/Personal/PersonalDetailsDelegate.swift
Blockchain/KYC/Personal/Service/PersonalDetailsService.swift
Blockchain/KYC/Storyboards/KYCPersonalDetailsController.storyboard
Blockchain/Network/NetworkManager.swift
Blockchain/Views/ValidationTextField/ValidationTextField.swift

Complete personal detail screen
Completing the personal details screen—previously, the network call made after tapping on "next" did not work because it was blocked by KYC authentication.
Other changes:
* Creating `KYCPageViewFactory` which is in charge of constructing a `KYCBaseViewController` given a `KYCPageType` and `KYCPayload`
* Creating `KYCPayload` and updating the `nextPageFromPageType`. The idea behind this is that when a page completes it can pass in a `KYCPayload` (e.g. thought of this so that we can pass around the data selected from `KYCCountrySelectionController`
1. Pull these changes in
2. Add `|| host == "api.dev.blockchain.info"` to `NetworkManager`
3. Launch KYC -> Select "Germany" -> Fill out personal details screen -> verify that you can get passed this step
NOTE: if …

feat(KYC): IOS-1167 attach authorization token to KYC personal details screen

---

Blockchain.xcodeproj/project.pbxproj
Blockchain/KYC/Address/API/LocationUpdateAPI.swift
Blockchain/KYC/Address/KYCAddressController.swift
Blockchain/KYC/KYCCoordinator.swift
Blockchain/KYC/KYCNetworkRequest.swift
Blockchain/KYC/Models/KYCPageModel.swift
Blockchain/KYC/Models/Network/KYCUpdateAddressRequest.swift
Blockchain/KYC/Personal/KYCPersonalDetailsController.swift
Blockchain/KYC/Search/LocationSuggestionCoordinator.swift
Blockchain/KYC/Search/Models/PostalAddress.swift
Blockchain/LocalizationConstants.swift

Complete KYC update address network call.
This PR completes the address update network call when a user tries to update their address during KYC. This was done by:
1. Providing the selected `KYCCountry` into `KYCAddressController`
2. Using `KYCAuthenticationService` to retrieve a session token followed by using that token to attach it to the "Authorization" header of the `PUT /users/current/address` network call
NOTE: this is reviewable but would like to merge #423 first before this PR (once #423 is merged, I'll update the base branch for this PR, I chose to base it off of `personal_details` to make reviewing easier)
1. Pull in these changes
2. Launch KYC
3. Select a homebrew supported country (e.g. Germany)
4. Go through personal details screen and hit next
5. Select an address and hit …

feat(KYC): IOS-1163 Complete update address network call.

---

Blockchain/KYC/KYCCoordinator.swift
Blockchain/KYC/KYCNetworkRequest.swift
Blockchain/KYC/Models/KYCPageType.swift

If the user already has set a phone number in their wallet, when they create a KYC user, they will already have those fields populated (no need to have them go through the enter/confirm phone # flow).
If the user already has set a phone number in their wallet, when they create a KYC user, they will already have those fields populated (no need to have them go through the enter/confirm phone # flow).
1. Create a wallet on dev on web (make sure to use a unique email address)
2. On web, set a phone number and verify it
3. Automatically pair your wallet on iOS and go through the KYC flow (make sure you are using the dev config values), notice that enter phone number is skipped
NOTE: since this requires the dev environment and dev certificates are not working, you'll ned to skip cert pinning by …

fix(KYC): IOS-1174 skip enter phone number if user already has a verified number.

---

Blockchain/KYC/Identity Verification/KYCVerifyIdentityController.swift
Blockchain/KYC/KYCCoordinator.swift
Blockchain/KYC/OnfidoController.swift

Launch KYC application complete screen after going through Onfido flow.
Go through KYC end-to-end.

fix(KYC): launch application complete screen after onfido flow.

---

Blockchain/KYC/Storyboards/Base.lproj/KYCApplicationCompleteController.storyboard

Adjust the font weight and label text color for the *Application Completed* screen.
Updated font weight and colors to match the designs. Also fixed the content scrolling behavior on smaller devices.
In `KYCCoordinator`, replace...
```
guard let welcomeViewController = pageFactory.createFrom(
pageType: .welcome,
in: self
) as? KYCWelcomeController else { return }
navController = presentInNavigationController(welcomeViewController, in: viewController)
```
with...
```
guard let applicationCompleteController = pageFactory.createFrom(
pageType: .applicationComplete,
in: self) as? KYCApplicationCompleteController else { return }
navController = presentInNavigationController(applicationCompleteController, in: viewController)
```

fix(KYC): IOS-1228 adjust font weight on application completed screen

---

Blockchain/Blockchain-Bridging-Header.h
Blockchain/Extensions/Bundle.swift
Blockchain/Extensions/NSAttributedString+Conveniences.swift
Blockchain/KYC/KYCWelcomeController.swift
Blockchain/Localization/Base.lproj/MainWindow.xib
Blockchain/LocalizationConstants.swift
Blockchain/Modal Content Views/BCCreateWalletView.h
Blockchain/Modal Content Views/BCCreateWalletView.m
Blockchain/Models/TransactionDetailViewModel.m
Blockchain/Network/BlockchainAPI.swift
Blockchain/View Controllers/BCWebViewController.m
Blockchain/View Controllers/BuyBitcoinViewController.m

- Add Privacy Policy link to Create Wallet View.
- Added `.com` and `.info` distinctions to `BlockchainAPI` `Hosts`, since the `BCWebViewController` was leaving the app due to the URLs being from `.com` instead of `.info`
~~Attempted to use this extension (https://github.com/blockchain/My-Wallet-V3-iOS/blob/kevin/IOS-1189/add_privacy_policy/Blockchain/KYC/KYCWelcomeController.swift#L100) to add a tappable view over attributed text, but it ends up being very offset for `.alignmentLeft`, even when the `textContainerOffset` is set to `0` as a user in the stackoverflow link suggests. Ended up using a pattern similar to the one in `PartnerExchangeConfirmViewController.m` to create tappable views over the Terms of Service and Privacy Policy. Unfortunately spent a lot of time on and havent found …

feat(CreateWalletView): IOS-1189 add privacy policy

---

Blockchain/Settings/Settings+Helpers.swift

To fix the text color of a verified badge in `formatDetailCell`.
Text color was green. Changed to white.
Verify your email and see white text on green badge.

fix(Settings): IOS-1192 change verified text color to white

---

Blockchain/KYC/Information/KYCInformationController.swift
Blockchain/KYC/KYCCoordinator.swift
Blockchain/KYC/Storyboards/KYCInformationController.storyboard

Add the missing close button to the account status view.
Launch the account status screen and dismiss it. Also observe that the entire KYC flow will be dismissed as well.

fix(KYC): add close button to account status view

---

Blockchain/LocalizationConstants.swift

Improve the error handling when an existing phone number is used.

fix(KYC): IOS-1190 improve error copy

---

Blockchain.xcodeproj/project.pbxproj

Disable bitcode in the project Build Settings.
Try to archive and submit the build (but let the team know first if you want to do this).
N/A

fix(Project): disable bitcode to match mach-o config with onfido

---

Blockchain/KYC/Information/KYCInformationViewModel.swift
Blockchain/Localization/Base.lproj/Settings.storyboard
Blockchain/Settings/Settings+Helpers.swift
Blockchain/Settings/Settings+Table.swift
Blockchain/View Controllers/Settings/SettingsCell.swift
Blockchain/View Controllers/Settings/SettingsViewController.swift

Fix the default identity verification status for newly created wallets.
Previously, the case for a new user was handled in the same way as a user with a `failed` state.
Create a new wallet and launch the settings view. Observe that the label inside the identity verification cell reads `Unverified` as opposed to `Failed`.

fix(KYC): IOS-1187 show correct verification status for new wallets

---

Blockchain/Homebrew/Exchange/DataProviders/ExchangeListDataProvider.swift
Blockchain/Homebrew/Exchange/Interactors/ExchangeListInteractor.swift
Blockchain/Homebrew/Exchange/Services/ExchangeService.swift
Blockchain/Homebrew/Exchange/Views/Cells/LoadingTableViewCell.swift
Blockchain/Homebrew/Exchange/Views/Cells/LoadingTableViewCell.xib
Blockchain/Homebrew/Exchange/Views/ExchangeListHeaderView.xib

This fixes some bugs in the exchange list screen, specifically around pagination
Fixed the following issues:
* Item added to the incorrect section
* `nextPage` function wasn't completing successfully as `result` wasn't updated with `.success(payload)`
* Fixed issue where the loading cell wasn't showing the activityIndicator animating. 
* Fixed issue where the header had a background color applied (this is deprecated per a console warning).
* Fixed an issue where we were continuing to fetch the `nextPage` even when the fetch was already in flight. 
Note: I actually stubbed out a sample payload and had to set a few `bool` properties in order to fake this. There's not a great way of testing this other than that. I can show a GIF though if that's needed. 
N/A

fix(HB): Fixes some bugs in handling pagination on the exchange list screen.

---

Blockchain/KYC/Identity Verification/KYCVerifyIdentityController.swift
Blockchain/KYC/Identity Verification/Service/OnfidoService.swift
Blockchain/KYC/KYCNetworkRequest.swift
Blockchain/KYC/OnfidoController.swift

Passing in the user's Onfido applicantId to Nabu/Blockchain upon submitting their identity docs.
Previously, the applicantId was not passed to the backend upon submitting identity docs to complete KYC processing.
Other changes:
* requiring the user to take a video rather than a selfie after submitting a capture of their identity card
* improving error logging in `KYCNetworkRequest` (i.e. prints to the console the error JSON we receive from the backend when we get a 4xx status code)
Launch KYC and go through the full steps. Unfortunately this is very difficult at the moment because KYC requires a unique mobile phone #.
N/A

feat(KYC): IOS-1173 passing in Onfido applicant ID to Blockchain

---

Blockchain/KYC/Storyboards/KYCCountrySelectionController.storyboard

Prevent copy from being cut off on smaller devices.
Changed the text label's `number of lines` attribute to allow the label to grow vertically.

fix(KYC): allow description label to grow vertically (IOS-1180)

---

Blockchain/Homebrew/Exchange/Services/MarketsService.swift
Blockchain/KYC/Address/KYCAddressController.swift
Blockchain/KYC/KYCCoordinator.swift
Blockchain/KYC/KYCPageViewFactory.swift
Blockchain/KYC/Mobile Number/KYCConfirmPhoneNumberController.swift
Blockchain/KYC/Mobile Number/KYCEnterPhoneNumberController.swift
Blockchain/KYC/Models/KYCPageModel.swift
Blockchain/KYC/Personal/KYCPersonalDetailsController.swift
Blockchain/LocalizationConstants.swift
Blockchain/Views/ValidationTextField/ValidationDateField/ValidationDateField.swift

Restoring KYC page stack if user drops off mid-flow.
**Note**: the base of this PR will be changed once #461 is merged.
This was done by inferring where the user is at during KYC by inspecting the Nabu user data. And depending on the page, the navigation controller is restored by pushing page view controllers wherein the top view controller is where the user left off.
Pull in these changes, go through KYC, drop off at some point, notice that the view state is restored.
N/A

feat(KYC): IOS-1142 restore view state if user drops of mid-flow.

---

Blockchain/KYC/Information/KYCInformationViewModel.swift
Blockchain/KYC/KYCCoordinator.swift
Blockchain/KYC/Models/KYCAccountStatus.swift
Blockchain/Settings/Settings+Helpers.swift

Add missing `UNDER_REVIEW` state to the KYC flow.

feat(KYC): add UNDER_REVIEW account state (IOS-1234)

---

Blockchain/Homebrew/Models/NabuUser.swift

Do not prefill the birthday field with the current date.
Debug KYC flow until personal details screen is reached and observe that the birthday field is initially empty again.
N/A

fix(KYC): do not prefill birthday field with current date (IOS-1264)

---

Blockchain/KYC/Address/KYCAddressController.swift
Blockchain/KYC/Search/Models/PostalAddress.swift

Pass the country code instead of the country name when updating the user.

fix(KYC): pass country code instead of name (IOS-1270)

---

Blockchain.xcodeproj/project.pbxproj
Blockchain/Coordinators/ExchangeCoordinator.swift
Blockchain/Homebrew/Exchange/API/ExchangeCreateContracts.swift
Blockchain/Homebrew/Exchange/Controllers/ExchangeCreateViewController.storyboard
Blockchain/Homebrew/Exchange/Controllers/ExchangeCreateViewController.swift
Blockchain/Homebrew/Exchange/DataProviders/ExchangeInputs.swift
Blockchain/Homebrew/Exchange/Interactors/ExchangeCreateInteractor.swift
Blockchain/Homebrew/Exchange/Models/InputsState.swift
Blockchain/Homebrew/Exchange/Models/NumberInputViewModel.swift
Blockchain/Homebrew/Exchange/Presenters/ExchangeCreatePresenter.swift
Blockchain/Homebrew/Exchange/Services/MarketsService.swift
Blockchain/Side Menu/SideMenuPresenter.swift

Add smaller label for fiat decimal amount input.
~~Added label to right-hand side of the primary amount label and display the decimal value when fiat input is switched on.~~~ EDIT: This will be deprecated using a more accurate approach using attributed text, but this PR still should be merged to avoid conflicts.
`InputsState` is also deprecated and is removed in active branches.
- Checkout 160de9607ccfb74ff9ab2df0ab601d089adc4d77 and open Exchange.
- Type some numbers
- Tap on the right-hand side button (currently text is truncated `...`) to switch to fiat
- Type more numbers after decimal
- Currently known that fiat symbol is missing and limit of 2 decimal places should be enforced for fiat - more changes are coming.
Not really close to designs at all yet other than amounts being …

feat(Homebrew-Exchange): add label for fiat decimal amount.

---

Blockchain/Constants.swift
Blockchain/Modal Content Views/BCCreateWalletView.m
Blockchain/View Controllers/DebugTableViewController.m

Optionally allow prefilled fields for the Create Wallet View in Debug mode.
Added Debug menu entry for enabling prefilled fields for the Create Wallet View.
Run app in a debug scheme, go to Create Wallet screen, see that fields are not pre-populated. Go to Debug menu, toggle the Create Wallet Prefill option ON, and see that fields are pre-populated.
N/A

feat(Debug): IOS-1263 optionally allow prefilled fields per QA request

---

Blockchain/View Controllers/SendEtherViewController.m

Allow closing of the keyboard on the Send Ether screen by tapping the right-hand side "X" button.
Renamed `closeButtonClicked` to `closeButtonTapped`. All other files that use this delegate method (`PartnerExchangeCreateViewController.m` and `ExchangeCreateView.swift` already implement `closeButtonTapped`.
Open Send Ether screen, tap on any field, and close keyboard with the X button on the input accessory view.
N/A

fix(Send-Eth): IOS-1277 use correct delegate method name

---

Blockchain/KYC/Information/KYCInformationController.swift
Blockchain/KYC/KYCCoordinator.swift

Upon KYC completion, take the user back to the status screen instead of showing the _Application Completed_ screen.

fix(KYC): take user directly to status screen (IOS-1266)

---

Blockchain/KYC/Identity Verification/KYCVerifyIdentityController.swift
Blockchain/KYC/Storyboards/KYCVerifyIdentityController.storyboard
Blockchain/LocalizationConstants.swift

Only show supported document types during identity verification step (passport and driver's license). Note that other document types are still in the code in case we add support at a later point.
Launch KYC flow and proceed to identity verification step. Verify that the there are only two supported document types.

fix(KYC): only show passport and driver's license options (IOS-1275)

---

Blockchain/KYC/KYCApplicationCompleteController.swift
Blockchain/KYC/KYCCoordinator.swift

Remove the back button from the _Application Completed_ screen.

fix(KYC): remove back button from application completed screen (IOS-1268)

---

Blockchain.xcodeproj/project.pbxproj
Blockchain/Arrays.swift
Blockchain/Extensions/Collection+Helpers.swift
Blockchain/KYC/Personal/KYCPersonalDetailsController.swift
Blockchain/KYC/Storyboards/Base.lproj/KYCPersonalDetailsController.storyboard
Blockchain/Views/ValidationForm/ValidationFormView.swift
BlockchainTests/Extensions/Collection+HelpersTests.swift

UI polish for the KYC personal details screen.
PR address the following issues:
* add 8pt vertical spacing between input fields
* move next button to bottom of the view
* auto-focus first name when entering screen (IOS-1217)
* allow scrolling up to previous input fields (the issue was that the UIScrollView's contentSize was set to 0 which prevented the UIScrollView's content from being scrollable)
* changing the background of the `UIProgressView` to be the default gray color instead of white
* modified the behavior of `ValidationFormView` so that when a input field is focused (i.e. the handler in `becomeFirstResponderBlock`) instead of scrolling it to the top of the scroll view, it will only scroll if and only if there is another `ValidationTextField` next/below it. Since this PR changes …

fix(KYC): IOS-1245 IOS-1217 IOS-1179 Personal details UI polish.

---

Blockchain/KYC/Search/LocationSuggestionCoordinator.swift

Polishing address entry screen in KYC flow.
* make UIScrollView scrollable (#475 is no longer blocked)
* don't show cancel button in search bar
* clearing search bar when tapping on result
Note: there is another polish task though which I was having trouble resolving (i.e. Pressing search on an empty input gives you an empty page (i.e. handle no results state)).
Launch KYC and go through address screen

fix(KYC): IOS-1246 address UI polish

---

Blockchain/Data/BlockchainDataRepository.swift

Update the cached nabu user when `fetchNabuUser()` function succeeds. This way, the cached nabu user is not stale when referenced.

fix(BlockchainDataRepository): update cache when fetchNabuUser succeeds.

---

Blockchain/KYC/Storyboards/KYCCountrySelectionController.storyboard

Update the title of the country selection screen.

fix(KYC): update country selection screen title (IOS-1283)

---

Blockchain/Settings/Settings+Table.swift

Fetch the latest nabu user when entering settings so we are displaying the most up-to-date info. Previously, we were displaying the cached nabu user which may be stale.

fix(KYC): fetch the latest nabu user when entering settings.

---

Blockchain.xcodeproj/project.pbxproj
Blockchain/Coordinators/ExchangeCoordinator.swift
Blockchain/KYC/CountrySelector/KYCCountrySelectionInteractor.swift
Blockchain/KYC/CountrySelector/KYCCountrySelectionPresenter.swift
Blockchain/KYC/Information/KYCInformationViewModel.swift
Blockchain/KYC/KYCCoordinator.swift
Blockchain/KYC/KYCNetworkRequest.swift
Blockchain/KYC/Storyboards/KYCInformationController.storyboard
Blockchain/LocalizationConstants.swift

Notifying server of user's country selection. This is needed for: (1) tracking the user's selection which is useful for us to know where drop-off happens, and (2) giving the user the option to have us notify them when exchange is available in their country.
Go through KYC, select a country, and verify that you see the log statement in the console "Successfully notified the server of the selected country.". Also, test that this log statement is also printed when tapping on "Message Me When Available" when the user selects a unsupported country (e.g. "Philippines")

feat(KYC): IOS-1250 Record selected country

---

Blockchain/Coordinators/ExchangeCoordinator.swift

Show shapeshift exchange if the user taps on a shapeshift supported country.
Fixes the issue wherein tapping on a country that is supported by shapeshift in the country selection screen does nothing.
Tap on exchange, go to the country selection screen, tap "United States", verify that you are taken to the old partner/shapeshift exchange flow.

fix(Exchange): show SS exchange if country is supported by shapeshift

---

Blockchain/Coordinators/ExchangeCoordinator.swift
Blockchain/Homebrew/Exchange/API/ExchangeListContracts.swift
Blockchain/Homebrew/Exchange/Controllers/ExchangeListViewController.swift
Blockchain/Homebrew/Exchange/DataProviders/ExchangeListDataProvider.swift
Blockchain/Homebrew/Exchange/Presenters/ExchangeListPresenter.swift

Present trade details view. Also fixed a bug wherein pulling to refresh would keep appending the same items.
Go to exchange, see past trades, tap on a trade.

feat(Exchange): present trade details when tapping on a trade item in exchange history

---

Blockchain/Homebrew/Exchange/API/ExchangeInputsAPI.swift
Blockchain/Homebrew/Exchange/Controllers/ExchangeCreateViewController.swift
Blockchain/Homebrew/Exchange/DataProviders/ExchangeInputComponent.swift
Blockchain/Homebrew/Exchange/Interactors/ExchangeCreateInteractor.swift
Blockchain/Homebrew/Exchange/Models/Fix.swift
Blockchain/Homebrew/Exchange/Models/InputComponent.swift
Blockchain/Homebrew/Exchange/Models/MarketsModel.swift
Blockchain/Homebrew/Exchange/Presenters/ExchangeCreatePresenter.swift
Blockchain/Homebrew/Exchange/Services/ExchangeConversionService.swift
Blockchain/Homebrew/Exchange/Services/ExchangeInputsService.swift

Fixing behavior of tapping on the swap button in `TradingPairView` to toggle the `Fix` value, and not the trading pairs.
**Primary Changes:**
* Added the appropriate methods in `MarketsModel`, `ExchangeCreatePresenter` and `ExchangeCreateInteractor` to toggle the Fix.
**Related Changes:**
* refactored the way the trading pairs are selected and refreshed in the views so that it propagates from the view controller, to the presenter, to the interactor, and back.
**Other notes:**
I noticed a few bugs and architecture issues that I didn't address to avoid blowing up the scope but wanted to call out. Namely:
(1) The didSet property observer method in `ExchangeCreateInteractor` for the property `model` might not be working as intended. Specifically, this block of code:
```
private(set) var …
```

feat(Exchange): IOS-1195 swap fix.

---

Blockchain.xcodeproj/project.pbxproj
Blockchain/Coordinators/ExchangeCoordinator.swift
Blockchain/Homebrew/Exchange/API/ExchangeDetailContracts.swift
Blockchain/Homebrew/Exchange/API/TradeExecutionAPI.swift
Blockchain/Homebrew/Exchange/Controllers/ExchangeDetailViewController.swift
Blockchain/Homebrew/Exchange/ExchangeDetailCoordinator.swift
Blockchain/Homebrew/Exchange/Interactors/ExchangeDetailInteractor.swift
Blockchain/Homebrew/Exchange/Presenters/ExchangeDetailPresenter.swift
Blockchain/Homebrew/Exchange/Services/TradeExecutionService.swift

Add live updates to the confirm screen.
On `dev` the `Conversion` currently only live updates on the `ExchangeCreateViewController`. Live updates also need to happen on the confirm exchange screen. Because the `Conversion` is always changing, the transaction is being rebuilt when tapping `Send Now` and sent immediately after.
In this PR, a new transaction will NOT be built with each `Conversion` message arriving.
Run exchange (mocking a deposit/deposit address if possible), create an exchange, then hit send now - the navigation controller should pop to the root view controller and the transaction should be shown as sent in the home transaction screen.
N/A

 feat(Homebrew-Exchange): IOS-1295 update confirm screen with conversion socket message info.

---

Blockchain.xcodeproj/project.pbxproj
Blockchain/Coordinators/ExchangeCoordinator.swift
Blockchain/Homebrew/Exchange/API/TradeExecutionAPI.swift
Blockchain/Homebrew/Exchange/API/TradeLimitsAPI.swift
Blockchain/Homebrew/Exchange/Controllers/ExchangeCreateViewController.storyboard
Blockchain/Homebrew/Exchange/Controllers/ExchangeCreateViewController.swift
Blockchain/Homebrew/Exchange/Interactors/ExchangeCreateInteractor.swift
Blockchain/Homebrew/Exchange/Presenters/ExchangeCreatePresenter.swift
Blockchain/Homebrew/Exchange/Services/MarketsService.swift
Blockchain/Homebrew/Exchange/Services/TradeExecutionService.swift
Blockchain/Homebrew/Exchange/Services/TradeLimitsService.swift
Blockchain/Homebrew/Exchange/Views/ExchangeCreateView.swift
Blockchain/LocalizationConstants.swift
Blockchain/Network/Models/SocketMessage.swift
Blockchain/Network/NetworkRequest.swift

Fetching trade limits and allowing the user to tap "Use min"/"Use max".
Tapping on "Use min"/"Use max" will:
* change the selected fix to `.baseInFiat`
* display the min/max based on the fiat value that is provided by `GET /trades/limits`
TODOs on my next PR:
* Pull in user's balance from the selected account and compare that balance against the trade limits
* Displaying error when user tries to proceed with trade but the amount is out of tradable bounds 
Other issue I found:
* ~Note that tapping on min/max will sometimes show the primary label incorrectly (i.e. if the min is 
"$1.16", it may show up as "$116". looks like `ExchangeInputService` sometimes doesn't report the entered text as `.fractionalInput`? Not entirely sure as I haven't spent too much time looking into it. Any ideas …

 feat(Exchange): IOS-1199 set use min/max text in create view.

---

Blockchain/Homebrew/Exchange/Interactors/ExchangeCreateInteractor.swift
Blockchain/Homebrew/Exchange/Services/MarketsService.swift
Blockchain/Network/Models/SocketMessage.swift
Blockchain/Network/SocketManager.swift

Unsubscribe to rates for currency pairs that are different from the pair the user is trying to exchange in.
Prevents chatty/extraneous websocket messages where conversion rates are still being received from previous currency pairs. This can happen if the user was previously trying to exchange in a currency pair (e.g. "BTC-ETH") but then changed to a different pair (e.g. "BCH-ETH"). 
Pull in changes, go to create exchange flow, change currency pairs, and verify that you see the logged message: "Pair <old pair> is different from model pair <new pair>"

fix(Exchange): unsubscribe from unused currency pair.

---

Blockchain/Accounts/AssetAccount.swift
Blockchain/Accounts/AssetAccountRepository.swift
Blockchain/AssetType.swift
Blockchain/Homebrew/Exchange/API/ExchangeCreateContracts.swift
Blockchain/Homebrew/Exchange/API/TradeLimitsAPI.swift
Blockchain/Homebrew/Exchange/Controllers/ExchangeCreateViewController.swift
Blockchain/Homebrew/Exchange/Interactors/ExchangeCreateInteractor.swift
Blockchain/Homebrew/Exchange/Presenters/ExchangeCreatePresenter.swift
Blockchain/Homebrew/Exchange/Services/MarketsService.swift
Blockchain/Homebrew/Exchange/Services/TradeLimitsService.swift
Blockchain/Network/Models/SocketMessage.swift
Blockchain/Network/SocketManager.swift

Checking account balances when populating min/max value that the user wishes to trade. Please review merge #515 before reviewing/merging this.
Previously, tapping on min/max will populate the trading limits for the user as provided get `GET /trades/limits`. However, this didn't take into account the balance of the user's account. In this PR, we are now computing the balance in fiat of the crypto the user wishes to trade.
This is done by:
* Getting the best exchange rates from the "exchange_rate" socket channel
* Taking the `AssetAccount` the user is exchanging from to retrieve the balance, followed by using the appropriate exchange rate to compute the balance in fiat.
Note that I exposed Rx methods in `TradeLimitsAPI` and `ExchangeMarketsAPI`. The reason I decided to Rx-ify here is …

feat(Exchange): IOS-1322 Checking balances when computing min/max

---

Blockchain/js/wallet-ios.js

Fix sending for a BCH exchange order.
Had JS add the `bitcoincash:` prefix required by the payment if the address is a BCH address.
Exchange from BCH - payment construction and send should go through.
N/A

fix(JS): add BCH prefix if using BCH address for exchanging

---

Blockchain/Homebrew/Exchange/Models/Order.swift
Blockchain/Homebrew/Exchange/Services/TradeExecutionService.swift
Blockchain/Network/Models/Result.swift
Blockchain/Network/NetworkRequest.swift

- Handle errors in a way similar to `KYCNetworkRequest`.
- Make `OrderResult` (the response from the trades endpoint) non-optional.
- Update `OrderResult` properties to match server response.
- Added error handling to `NetworkRequest`'s `execute` method.
- Removed optionals and error-related properties from `OrderResult`.
- Removed force unwraps of `OrderResult` properties from `TradeExecutionService`.
Hit a bad endpoint and see an error instead of an attempt to decode to a certain type.
N/A

fix(NetworkRequest): error if bad response or status code

---

Blockchain/Homebrew/Exchange/API/ExchangeInputsAPI.swift
Blockchain/Homebrew/Exchange/Controllers/ExchangeCreateViewController.swift
Blockchain/Homebrew/Exchange/ExchangeDetailCoordinator.swift
Blockchain/Homebrew/Exchange/Interactors/ExchangeCreateInteractor.swift
Blockchain/Homebrew/Exchange/Models/MarketsModel.swift
Blockchain/Homebrew/Exchange/Services/ExchangeInputsService.swift
Blockchain/Homebrew/Exchange/Services/MarketsService.swift
Blockchain/Network/Models/SocketMessage.swift
Blockchain/Settings/BlockchainSettings.swift

Use correct fiat symbols in the exchange flow.
- Used fiat symbol from wallet object through `BlockchainSettings` instead of USD.
- Used the `fiatCurrency` stored in `MarketsModel` instead of `NumberFormatter`'s `currencySymbol`
- Used `fiat.value` from `conversion.quote.currencyRatio`'s `base` or `counter` for display
- Replaced the ambiguous `fiatCurrency` property on `MarketsModel` with `fiatCurrencySymbol` ($, £) and `fiatCurrencyCode` (USD, GBP).
- Go to Exchange with a few different Local Currency options set in Settings. See the currency symbol displayed in the input labels.
- Go to the confirm screen and see that the appropriate currency symbol is displayed.
Not able to test at the moment due to server issues.
Brazil Real as an example:

feat(Homebrew-Exchange): use fiat symbol from wallet settings

---

Blockchain/Accounts/AssetAccount.swift
Blockchain/Homebrew/Exchange/Controllers/ExchangeCreateViewController.swift

All currency options should show when selecting a trade option. 
We're no longer filtering against the selected asset. Also, if they select the asset that matches the other asset in the pair, we swap the two assets. 
2. Go to the exchange
3. Tap either asset
4. All asset types should be shown
N/A

feat(HB): IOS-1312 - All currencies should show when selecting source

---

Blockchain/Accounts/AssetAccountRepository.swift
Blockchain/Blockchain-Bridging-Header.h
Blockchain/Homebrew/Exchange/Controllers/ExchangeDetailViewController.swift
Blockchain/Homebrew/Exchange/ExchangeDetailCoordinator.swift
Blockchain/Homebrew/Exchange/Models/CellModels/ExchangeCellModel.swift
Blockchain/Homebrew/Exchange/Models/CellModels/ExchangeTradeCellModel.swift
Blockchain/Homebrew/Exchange/Models/Order.swift
Blockchain/Homebrew/Exchange/Services/TradeExecutionService.swift
Blockchain/Homebrew/Exchange/Views/Cells/DetailCollectionViewCells/Plain/PlainCell.swift
Blockchain/Homebrew/Exchange/Views/Cells/DetailCollectionViewCells/Plain/PlainCell.xib
Blockchain/Homebrew/Exchange/Views/Cells/ExchangeListViewCell.swift
Blockchain/LocalizationConstants.swift
Blockchain/Settings/BlockchainSettings.swift

Update the detail screen for the Exchange List view controller.
- Updated model and cells for order detail.
- Minor fixes and refactoring in the `ExchangeDetailCoordinator`.
- Added tap gesture and small animation to copy order ID to clipboard.
Go to Exchange List controller and tap on a transaction. If server is down, cherry-pick 3975b4c74 to show a mock transaction.
Not there 100%, but the essential data is there. (Put your own address as `withdrawalAddress` in the mock data to test Send To)

feat(Homebrew-Exchange): IOS-1311 update order detail model and cells

---

Blockchain/AppDelegate.swift
Blockchain/Network/Extensions/NetworkManager+PushNotifications.swift

Restore the ability to register the device for push notifications with the back-end.
Implemented `didRegisterForRemoteNotificationsWithDeviceToken` to get the device token and make a call to `registerDeviceForPushNotifications` in `NetworkManager`.
On device only, create a new wallet and accept the push notification permission alert.
N/A

fix(Notifications): restore device registration for push notifications

---

Blockchain/Homebrew/Exchange/DataProviders/ExchangeListDataProvider.swift
Blockchain/Homebrew/Exchange/Views/Cells/NewOrderTableViewCell.xib

Fixes the selection style of `NewOrderTableViewCell` and fixes selecting the incorrect `indexPath` shows the `ExchangeOverview` screen. 
2. Go to the new exchange flow
3. Select the `New Order` cell (but don't tap the button). 
4. It should not show a selection style and it should not show the `ExchangeOverview` screen

fix(HB): Fixes issue where tapping New Exchange showed exchange details.

---

Blockchain/Coordinators/AppCoordinator.swift
Blockchain/Coordinators/ExchangeCoordinator.swift

Fix bug where previous Nabu user not being cleared when logging out, and creating a new wallet. 
Create a wallet, go through KYC, log out, create new wallet, verify that when tapping on "Exchange" you are forced to go through the KYC process again.

fix(KYC): IOS-1269 fix previous Nabu user not being cleared when creating a new wallet.

---

Blockchain.xcodeproj/project.pbxproj
Blockchain/Views/Buttons/BounceButton.swift
Blockchain/Views/Keypad/NumberKeypadView.xib

Shows a small transform animation when the user taps on a button in the number pad.
The buttons in `NumberKeypadView` are now `BounceButtons` which scale up or down depending on their selection state. 
2. Go to the exchange screen
3. Interact with the number pad.
4. The buttons should animate.

feat(HB): Adding `BounceButton`

---

Blockchain/KYC/KYCCoordinator.swift

Correctly present the `ExchangeCoordinator` on the _account approved_ screen, when the user taps on **Get Started**.
By storing a reference to the rootViewController, the `ExchangeCoordinator` is able to be presented correctly.
Using a verified user, open Settings and tap on the _Identity Verification_ cell. On the _Account Approved_ screen, tap **Get Started**. Observe that it presents the Exchange correctly.

fix(KYC): correctly present ExchangeCoordinator

---

Blockchain/Coordinators/ExchangeCoordinator.swift
Blockchain/KYC/CountrySelector/KYCCountrySelectionController.swift
Blockchain/Models/TabControllerManager.h
Blockchain/View Controllers/PartnerExchangeListViewController.h
Blockchain/View Controllers/PartnerExchangeListViewController.m

When selecting a country that is supported by SS (e.g. Andorra), do not display the state picker screen.
Fixes an issue where we would display the state picker screen regardless of the user's country selection when launching the partner exchange flow. The reason this was happening was because we were using the country guess which is based on the IP address of the user. This PR fixes that since we no longer need to make guesses.
Note that we are still using country/state guess to optionally show the Exchange side menu item. So, if the country/region the user is in is blacklisted and should not be able to use shapeshift, they won't be able to see the Exchange option.
Pull in changes, tap on a country that is supported by Shapeshift (e.g. Andorra), verify that you don't need to select a …

fix(KYC): Don't display state picker if selected country is not in the US (IOS-1330)

---

Blockchain/Homebrew/Exchange/API/ExchangeCreateContracts.swift
Blockchain/Homebrew/Exchange/Controllers/ExchangeCreateViewController.swift
Blockchain/Homebrew/Exchange/Interactors/ExchangeCreateInteractor.swift
Blockchain/Homebrew/Exchange/Models/MarketsModel.swift
Blockchain/Homebrew/Exchange/Presenters/ExchangeAssetAccountListPresenter.swift
Blockchain/Homebrew/Exchange/Presenters/ExchangeCreatePresenter.swift

This fixes a bug where users who had multiple wallets of the same asset type could not select alternate wallets. e.g. A user trading from BTC to ETH who had a secondary ETH wallet could not select the secondary ETH wallet in the picker. 
We were filtering based on the `TradingPair` of the `MarketsModel`. I've added `MarketPair` which houses a `fromAsset` and `toAsset`. When the user taps on the `TradingPairView` to select a different wallet, instead of filtering on the `assetType`, we now filter out the `AssetAccount`. 
2. Sign into an account with multiple wallets of the same type
3. Go to the exchange screen
4. Try to select different wallets of the same type
**Note: You should still not be able to trade between accounts of the same asset type**
N/A

fix(HB): IOS-1312 - All accounts should show in the alert controller

---

Blockchain/Homebrew/Exchange/Controllers/ExchangeCreateViewController.storyboard

Keyboard is too tall - goal is to adjust to a proportionally smaller size.
With the keyboard height changing I made some changes to the fiat button and the input labels as well.
- Added constraint - Keypad view to be 37.5% of superview's height (turns out that 40% makes the 5S input labels overlap a tiny bit)
- Removed fiat button image insets (turned out to be way too unmaintainable) and instead gave it constant width/height and had it run over the edge of the screen.
- To give the impression of the image view being aligned with the right-hand side safe area margin similarly to the other subviews, added a constraint for its center to be 1.25x the horizontal center of the Use Max button.
- Vertically centered fiat button with primary amount label instead of secondary amount label to match …

fix(Homebrew-Exchange): IOS-1346 adjust keyboard height to 37.5% of superview

---

Blockchain/Modal Content Views/BCCreateAccountView.m

Fixes bug where user cannot create another account.
User was not able to create a new account because the entered account label was being evaluated as an email address. Looks like it may have been added by accident in bf0eb1d. Found this issue while testing #534 
Pull in changes, try to create account (Tap "Addresses" in the side menu -> "+" button in the Wallets header for Bitcoin), and verify that it succeeds.

fix(Account): remove 'Invalid email address' alert when creating another account

---

Blockchain/Coordinators/ExchangeCoordinator.swift
Blockchain/View Controllers/PartnerExchangeListViewController.h
Blockchain/View Controllers/PartnerExchangeListViewController.m

Fixes issue where partner exchange cannot be launched when tapping on the exchange side menu. This was a regression introduced in 91891143.
Launch the app with an approved nabu user (but have "enable homebrew" in the debug options turned off), tap on "Exchange", verify that the partner exchange is launched.

fix(Exchange): fix issue where partner exchange can't be launched.

---

Blockchain/View Controllers/SendEtherViewController.m

Fixes a crash when sending ETH
`continueButton` was calling `continueButtonClicked` rather than `continueButtonTapped`.
2. Tap `Send`
3. Select `ETH`
4. Tap `Continue`
5. It should not crash. 
N/A

fix(Send): IOS-1314 - Fixing unrecognized selector crash

---

Blockchain/Constants.swift
Blockchain/Extensions/DateFormatter+Conveniences.swift
Blockchain/Homebrew/Exchange/Controllers/ExchangeListViewController.swift
Blockchain/Homebrew/Exchange/ExchangeDetailCoordinator.swift
Blockchain/Homebrew/Exchange/Interactors/ExchangeListInteractor.swift
Blockchain/Homebrew/Exchange/Models/CellModels/ExchangeCellModel.swift
Blockchain/Homebrew/Exchange/Models/CellModels/ExchangeTradeCellModel.swift
Blockchain/Homebrew/Exchange/Models/TradingPair.swift
Blockchain/Homebrew/Exchange/Services/ExchangeService.swift
Blockchain/Homebrew/Exchange/Services/HomebrewExchangeService.swift
Blockchain/Homebrew/Exchange/Views/Cells/DetailCollectionViewCells/Plain/PlainCell.swift

Fixes issue where we were not showing the user's order history.
This endpoint requires a different date format than our session token endpoint. Additionally, some of the values on our trade model need to be optional. Lastly, there's an issue with the `pair` property. You're not supposed to ever have a pair with two of the same asset types. However, there was a server side bug where this could feasibly happen. This has been fixed on the server however, if you did submit trades while this bug was still around, you would get an assertion as `pair` would be nil. 
I'm waiting to hear from the backend team to see if these trades could be purged. 
2. Go to the Exchange List screen
3. If you've submitted trades on HB, you should see those trades now.
4. Try pulling to refresh. …

fix(Order history): IOS-1339 - Not showing pending trade

---

Blockchain/Homebrew/Exchange/API/ExchangeCreateContracts.swift
Blockchain/Homebrew/Exchange/API/TradeExecutionAPI.swift
Blockchain/Homebrew/Exchange/ExchangeDetailCoordinator.swift
Blockchain/Homebrew/Exchange/Interactors/ExchangeCreateInteractor.swift
Blockchain/Homebrew/Exchange/Presenters/ExchangeCreatePresenter.swift
Blockchain/Homebrew/Exchange/Services/TradeExecutionService.swift
Blockchain/Models/Wallet.h
Blockchain/Models/Wallet.m

Fixes an issue where multiple trades could be submitted on the `Exchange - Send Now` screen.
This PR adds an `isExecuting` property to the `TradeExecutionAPI`. It also adds some completion handlers to the `Wallet` class to allow `TradeExecutionService` to update its `isExecuting` property when the `Wallet` completes exchange submissions. 
2. Go to the exchange
3. Create an exchange
4. Tap `Send Now` quickly, twice. 
5. See that a loading indicator is shown preventing the user from multiple taps
6. See that the `isExecuting` property is `true` when a request is in flight, and thus returns early. 
N/A

fix(HB): Fixing issue where multiple trades could be submitted.

---

Blockchain.xcodeproj/project.pbxproj
Blockchain/Network/Models/SocketMessage.swift
BlockchainTests/Network/Models/SocketMessageTests.swift

Fix min/max not working on exchange create view.
The reason this was breaking was because the server now returns best rates as a string rather than a number.
Go to exchange, tap min/max, verify that you see it working.

fix(Exchange): compute min/max (IOS-1361)

---

Blockchain/Coordinators/ExchangeCoordinator.swift
Blockchain/Homebrew/Exchange/Controllers/ExchangeDetailViewController.swift
Blockchain/Homebrew/Exchange/ExchangeDetailCoordinator.swift
Blockchain/Homebrew/Exchange/Interactors/ExchangeCreateInteractor.swift
Blockchain/Homebrew/Exchange/Interactors/ExchangeDetailInteractor.swift

Make sure all amount label are cleared when returning to the New Exchange screen from the list controller.
~Cleared the secondary amount label on `viewDidLoad`. Looking for feedback on whether this is the best place for it inside this method.~
Found out that the state of the secondary output is retained in the `ExchangeConversionService`. Discussion with @bchrisarriola concluded that it would be best to inject `ExchangeServices` to ensure new instances for each.
Also did a little cleaning up:
- The `ExchangeDetailInteractor` doesn't need the `ExchangeConversionService` so I removed that.
- The `ExchangeDetailViewController.PageModel` doesn't need to be instantiated with dependencies now that the `ExchangeDetailCoordinator` has it, so I removed the dependencies parameter from the …

fix(Homebrew-Exchange): IOS-1358 make ExchangeCoordinator inject ExchangeServices into view controllers

---

Blockchain/KYC/Address/KYCAddressController.swift

Fixes an issue where autocomplete could leave a blank address field.
If the address didn't contain a street number or street address, we populated the field with two empty strings and a space. This caused the placeholder to no longer be visible. Now we only populate the field if there is a valid street number and street address. 
2. Go through KYC
3. Use the autocomplete feature in the address screen
4. Select an address
5. It should autopopulate.
N/A

fix(KYC): IOS-1310 - Autocomplete leaves address field blank

---

Blockchain.xcodeproj/project.pbxproj
Blockchain/Homebrew/Models/NabuNetworkError.swift
Blockchain/KYC/KYCNetworkRequest.swift
Blockchain/Network/HTTPRequestError/HTTPRequestError.swift
Blockchain/Network/NetworkRequest.swift

Created `NabuNetworkError` to allow closer inspection on 4xx type HTTP errors returned by the server.
Nabu returns us a very specific error code when a network request fails. For example, we get the following error message when trying to go through the exchange flow with an email associated to a wallet:
```
{
"id":"someId",
"code":33,
"type":"CONFLICT",
"description":"User already exists"
}
```
At the moment, the client simply logs these kind of messages and does not propagate it back up to the caller of the network request.
With `NabuNetworkError`, callers can now have closer inspection on the error message returned by the server which in turn allows us to show a more user-friendly error message to the user. At the moment, it isn't used anywhere but wanted to get this PR in so that we …

feat(NabuNetworkError): unmarshall error payloads returned by Nabu into NabuNetworkError, if possible

---

Blockchain/Homebrew/Exchange/Interactors/ExchangeCreateInteractor.swift
Blockchain/Homebrew/Exchange/Services/MarketsService.swift
Blockchain/Network/Models/SocketMessage.swift
Blockchain/Network/SocketManager.swift

This is a progress PR for adding in some error handling in `SocketManager`. 
This PR includes the addition of `SocketError` as well as `ExchangeInteractor` subscribing to the error payloads returned by `SocketManager`. Note that this PR does not include UI updates in response to the returned errors. 
I also dialed back the logging a bit in `SocketManager`. I'm filtering out `Heartbeat` types as it was getting a bit noisy in the console log. 
2. Go to the new exchange
3. Begin entering in some small values. You should see errors returned in the console log. e.g. `Decoded socket message of type SocketError`
4. Enter in a value that is within the appropriate limits (max/min). You should see the correct conversion. 
N/A

fix(HB): IOS-1319 - Adding `SocketError` and error subscribing to `ExchangeInteractor`

---

Blockchain/Homebrew/Exchange/Controllers/ExchangeListViewController.swift
Blockchain/Homebrew/Exchange/Models/CellModels/ExchangeTradeCellModel.swift
Blockchain/Homebrew/Exchange/Views/Cells/ExchangeListViewCell.swift

Fixes an issue where `withdrawal` is `nil` in the event of a failed trade. Also fixes some UI issues including a incorrect color for a back button and missing currency symbols. 
2. Go to the Exchange List
3. See that you can now see your prior exchanges (even the failed ones)
Design is still TBD for handling `Failed` state. Likely remains the same but possible that `zero` is inserted vs `nil` to account for a trade that didn't complete.

fix(HB): IOS-1368 - `Withdrawal` SymbolValue can sometimes be nil resulting in no trade history

---

Blockchain/KYC/Identity Verification/KYCVerifyIdentityController.swift
Blockchain/KYC/KYCCoordinator.swift
Blockchain/KYC/Models/KYCPageModel.swift

Fix bug where use cannot continue through KYC if they drop-off right at the verify identity step.
This was previously failing because the user's country selection, which is just stored in memory, can be dealloc'd if the user drops off right before the verify identity step. The fix is to instead pass around the country code which can be recovered from the user's address.
1. Create a new wallet
2. Go through KYC and drop-off right before the identity verification step (kill the app)
3. Go back to KYC, and verify that you can continue
N/A

fix(KYC): fix bug where user cannot continue with KYC (IOS-1321).

---

Blockchain.xcodeproj/project.pbxproj
Blockchain/Homebrew/Exchange/Services/MarketsService.swift
Blockchain/Network/SocketManager.swift
BlockchainTests/Homebrew/Exchange/Services/MarketsServiceTests.swift
BlockchainTests/Mock/MockSocketManager.swift

Close exchange WS when no longer needed.
Fixes issue where quote related WS messages were still received even when the user is no longer on the exchange create screen.
Note about unit tests and directory structures... The location of the test file should mimic the location and directory structure of the file being tested (e.g. https://cloudup.com/cD9DjzafCct).
1. Go to exchange create
2. Verify that you see "Websocket connected..."
3. Exit out of exchange
4. Verify that you see "Websocket disconnected..."

fix(Websocket): close exchange WS when no longer needed.

---

Blockchain/Accounts/AssetAccountRepository.swift
Blockchain/Homebrew/Exchange/Controllers/ExchangeDetailViewController.swift
Blockchain/Homebrew/Exchange/ExchangeDetailCoordinator.swift
Blockchain/Homebrew/Exchange/Models/CellModels/ExchangeTradeCellModel.swift
Blockchain/Homebrew/Exchange/Views/Cells/ExchangeListViewCell.swift
Blockchain/Models/ExchangeTrade.h
Blockchain/Models/ExchangeTrade.m

Multiple fixes for incorrectly formatted trade overview details.
There were a bunch of minor things here: 
* We were comparing wallet addresses without taking into account casing. 
* The extension on `ExchangeTradeModel` was returning an empty string for a few values when the model type was of `.partner`
* The functions that are on the `ExchangeTrade` extension were using `BlockchainSettings.shared.symbolLocal`. This was correct in the case that we're using `ExchangeTableViewCell`, but we aren't. I broke up those functions to be a bit more descriptive and easier to follow. That settings value was actually `nil` but we were using the function for both fiat and crypto when both fiat *and* crypto should be displayed simultaneously (not toggled like the older design). 
* Now taking into …

fix(OrderHistory) - IOS-1343 - Order history fields for partner trades were blank and/or incorrect 

---

Blockchain/Authentication/AuthenticationCoordinator.swift
Blockchain/Authentication/Views/PasswordConfirmView.swift
Blockchain/Coordinators/ExchangeCoordinator.swift
Blockchain/Homebrew/Exchange/Services/TradeExecutionService.swift
Blockchain/Models/TransferAllFundsBuilder.m
Blockchain/Models/Wallet.h
Blockchain/Models/Wallet.m
Blockchain/Wallet/WalletManager.swift
Blockchain/Wallet/WalletSecondPasswordDelegate.swift
Blockchain/js/wallet-ios.js

Allow creating and sending exchange order with second password.
- Added property `dismissHandler` to `PasswordConfirmView` to allow setting `tradeExecution.isExecuting` back to `false` after dismissing `PasswordConfirmView`
- Fixed issue where `bitcoincash:` prefix could be added twice
- Fixed some missing parameter bugs in JS
Submit and send an exchange order with second password enabled.
N/A

fix(Homebrew-Exchange): IOS-1348 add dismiss handler to password confirm view

---

Blockchain.xcodeproj/project.pbxproj
Blockchain/Extensions/Rx+Helpers.swift
Blockchain/Homebrew/Exchange/API/ExchangeCreateContracts.swift
Blockchain/Homebrew/Exchange/Controllers/ExchangeCreateViewController.storyboard
Blockchain/Homebrew/Exchange/Controllers/ExchangeCreateViewController.swift
Blockchain/Homebrew/Exchange/Interactors/ExchangeCreateInteractor.swift
Blockchain/Homebrew/Exchange/Services/MarketsService.swift
Blockchain/Network/Models/SocketMessage.swift

Display best crypto-to-crypto and crypto-to-fiat exchange rates
Summary of changes:
* Display best rates as provided by the "exchange_rates" websocket end-point (previously, these rates were only used to convert balances to fiat). Using these rates, we can display the conversion rate for the selected trading pair.
Other changes:
* Added an extension to `CompositeDisposable` to allow discardable result inserts
* Note that the "exchange_rates" websocket does not return the fiat symbol, the consequence of this is that crypto to fiat rates are displayed as "1 BTC = 123 USD" and not "1 BTC = $123" (confirmed with design that this behavior is fine). 
1. Pull in changes
2. Try selecting different trading pairs
3. Verify that conversions update

fix(Exchange): update conversion rates view as rates and trading pairs change (IOS-1364)

---

Blockchain/Coordinators/ExchangeCoordinator.swift
Blockchain/KYC/CountrySelector/KYCCountrySelectionController.swift

Dismiss KYC navigation stack when starting partner exchange flow
Launch KYC, pick an SS-supported country (e.g. Andorra), notice that KYC nav stack is dismissed first.

fix(KYC): dismiss KYC navigation stack when starting partner exchange flow (IOS-1337).

---

Blockchain/Coordinators/AppCoordinator.swift
Blockchain/Models/Wallet.h
Blockchain/Models/Wallet.m
Blockchain/js/wallet-ios.js

Fix issue where creating an HD account resulted in zero balances displayed in the dashboard and transactions tab.
After a successful wallet backup, the views were reloading while balances were `null`. Made `getHistoryForAllAssets` public and called it in `didBackupSuccess` and `didBackupError`. Also removed a couple of busy view and reload calls since `getHistoryForAllAssets` will ultimately hide the busy view.
Create an HD account in Addresses, and see that the balances are unchanged.
N/A

fix(Wallet): IOS-1387 fetch balances after sync

---

Blockchain/Homebrew/Exchange/Controllers/ExchangeCreateViewController.swift

Change default fix to `.baseInFiat`
Launch exchange and notice that fiat is the new default.

fix(Exchange): change default fix to baseInFiat (IOS-1359)

---

Blockchain/Homebrew/Exchange/Views/Headers/ExchangeLockedHeaderView.xib

The `X` button on the `Exchange Locked` screen was 22x22. This has been bumped up to 40x40 to make it easier to tap. 
2. Create an exchange
3. Submit an exchange
4. Tap the `X` on the exchange locked screen

fix(HB): IOS-1340 - Increasing tap area of `X` in `Exchange Locked`

---

Blockchain/Extensions/DateFormatter+Conveniences.swift
Blockchain/Homebrew/Exchange/Models/CellModels/ExchangeTradeCellModel.swift

Fixes an issue where some trades have a `createdAt` date format that doesn't produce a string value when using the `sessionDateFormatter`
Using an account provided by QA, I saw that some trades use this format: 
`"2018-10-03T16:02:45.435Z"`
Other trades use this format:
`"2018-10-02T22:07:38Z"`
Our session date formatters uses this format: `yyyy-MM-dd'T'HH:mm:ss.SSSZ`
I added an `ISO8601DateFormatter` and it produces a string value for the second format. 
1. Build and run in staging
2. Use the account cited by QA in the ticket
3. Go to the exchange history screen
4. See that trades are now showing

fix(HB): IOS-1368 - trade date formatter fix

---

Blockchain/Homebrew/Exchange/API/ExchangeListContracts.swift
Blockchain/Homebrew/Exchange/Controllers/ExchangeListViewController.swift
Blockchain/Homebrew/Exchange/Presenters/ExchangeListPresenter.swift
Blockchain/Homebrew/Exchange/Services/ExchangeService.swift
Blockchain/LocalizationConstants.swift

Show user friendly error when fetching trades fails.
- Implemented `ExchangeListOutput` method `tradeFetchFailed(error: Error?)`
- Implemented `ExchangeListInterface` method `showError(message: String)`
Cherry pick d9fba74e300c91b4dfc5f7cfadaa33a459c5ece8
Go to Exchange, pull to refresh - you should see an error.
N/A

fix(ExchangeListViewController): IOS-1385 show error message when fetching trades fails

---

Blockchain/Homebrew/Exchange/Controllers/ExchangeCreateViewController.storyboard
Blockchain/Homebrew/Exchange/Controllers/ExchangeCreateViewController.swift
Blockchain/Homebrew/Exchange/Presenters/ExchangeCreatePresenter.swift

- Remove placeholder text for conversion title label.
- Fade in display rate for conversion title label.
- Speed up toggle to display rates.
Go to Exchange.
- Observe that the display rate is not populated with placeholder text
- Observe that the display rate fades in
- When tapping on the display rate, the animation for showing the rates happens at a reasonably fast speed.
N/A

fix(Homebrew-Exchange): IOS-1363 UI fixes to display rates

---

Blockchain/Extensions/UIView.swift
Blockchain/Homebrew/Exchange/API/ExchangeCreateContracts.swift
Blockchain/Homebrew/Exchange/Controllers/ExchangeCreateViewController.storyboard
Blockchain/Homebrew/Exchange/Controllers/ExchangeCreateViewController.swift
Blockchain/Homebrew/Exchange/Interactors/ExchangeCreateInteractor.swift
Blockchain/Homebrew/Exchange/Presenters/ExchangeCreatePresenter.swift
Blockchain/LocalizationConstants.swift
Blockchain/Network/Models/SocketMessage.swift

We now check the user's balance of the `from` account prior to creating a payment.
When creating an exchange, if the user enters in a fiat or crypto amount that is greater than what they have in their account, an error will be displayed. We check the `volume` of the `Conversion` and compare it to `account.balance`. 
2. Go to the exchange 
3. Enter in an amount that is greater than what's in your account
4. You should see an error showing your account's balance in crypto.

fix(HB): 1338 - Checking user account balance before creating a payment

---

Blockchain/Homebrew/Authentication/NabuAuthenticationService.swift

Attempt to fix the issue wherein nabu returns the following error:
```
["description": Can not process auth request, token can not be found, "channel": auth, "type": error, "sequenceNumber": 0]
```
One of the scenarios wherein the server can return that error is if the client sends an expired token to the server. Since the server's clock and the phone's clock can be slightly off (i.e. the server might read time at "4:00.00 pm" but the client's clock might be at "3.59.30 pm"), the client might be sending expired tokens which result in failed WS auth calls. To prevent this, this PR subtracts 30 seconds off the expiration time comparison on the client so that the client will just request a new session token if it's within < 30 seconds of the expiration time in the phone's frame of reference. …

fix(Session Token): subtract 30 seconds from expiration time when trying to reuse cached token

---

Blockchain/Homebrew/Exchange/Services/PartnerExchangeService.swift

Fixes a bug where `.error(nil)` was returned in a completionBlock when really it should be `.success([])` as the call to fetch partner trades completed successfully but there were no trades. 
N/A (Unless you've never done an SS trade, which in that case go to the exchange history screen and refresh your trades. You shouldn't see an alert.)
N/A

fix(HB): Fix issue where receiving zero trades from SS showed an error.

---

Blockchain/Homebrew/Exchange/DataProviders/ExchangeListDataProvider.swift
Blockchain/Homebrew/Exchange/Services/HomebrewExchangeService.swift

Fixes an issue where we weren't fetching the next page correctly in trade history.
The incorrect date formatter was used in fetching the next page of exchanges. 
2. Sign into account referenced in ticket
3. Go to the trade history screen
4. Scroll. It should paginate. It should show older trades. It should eventually get to the last page and stop. 
N/A

fix(HB): IOS-1402 - Fixing trades not paginating correctly

---

Blockchain/Constants.swift
Blockchain/Homebrew/Exchange/Controllers/ExchangeDetailViewController.swift
Blockchain/Homebrew/Exchange/ExchangeDetailCoordinator.swift
Blockchain/Homebrew/Exchange/Models/CellModels/ExchangeTradeCellModel.swift
Blockchain/LocalizationConstants.swift

Add refund button to expired trades and link to support ticket request page.
- Added description sections for expired and failed trades.
- Added button for expired trades to open an `SFSafariViewController` to the support page.
- Go to Exchange
- See that all trade detail views are viewable from the `ExchangeListViewController`
- See that descriptions are shown for expired and failed trades.
- See that a request refund option is available for expired trades and that it opens the support page.

feat(ExchangeDetailViewController): IOS-1393 add refund button to expired trades.

---

Blockchain/Homebrew/Exchange/Interactors/ExchangeCreateInteractor.swift

Another attempt at fixing WS auth failure. 
My hypothesis is that another reason WS auth can fail is because of a race condition wherein the token we are sending for WS auth is invalidated since another request (i.e. the request to get trade limits), may be interfering and requesting a _new_ session token.
This PR mitigates that issue by first waiting for the WS auth to complete before requesting a token from `NabuAuthenticationService`.
Jump in and out of exchange create view and notice you don't get the WS auth error.

fix(WS Authentication): fix WS auth failures (IOS-1405)

---

Blockchain/KYC/Search/Models/PostalAddress.swift

Allow KYC verified users to use Exchange.
Fixed issue where KYC users without a `lineTwo` of the `PostalAddress` filled would see an alert with the error "The data couldn’t be read because it is missing”
Go through KYC but do not fill in line 2 of the address ("APT, Floor, #"). After getting verified, you should be able to tap on the Exchange side menu item without seeing an error.
N/A

fix(Homebrew-KYC): IOS-1370 make line 2 of address optional

---

Blockchain.xcodeproj/project.pbxproj
Blockchain/Lockbox/LockboxRepository.swift
Blockchain/Lockbox/Models/Lockbox.swift
Blockchain/Lockbox/Models/LockboxAccount.swift
Blockchain/Lockbox/Models/LockboxAsset.swift
Blockchain/Lockbox/Models/LockboxDeviceType.swift
Blockchain/Models/Wallet.h
Blockchain/Models/Wallet.m
Blockchain/js/wallet-ios.js

Creating `Lockbox` and associated models.
If a user has synced a lockbox device on their wallet, this will appear under the key "lockbox" in their wallet metadata. This PR adds the native models so that this object can be unpacked to swift models. This unblocks the lockbox feature in that all that is required from here is UI related changes.
Getting access to the wallet's lockboxes can be done by:
```
let repo = LockboxRepository()
let lockboxes = repo.lockboxes()
```
TODO: I want to add unit tests in deserializing `Lockbox` but didn't have much time. Will get to that in another PR.
_Note: Please test with a wallet that doesn't have lockboxes, and a wallet that has a synced lockbox/es_
1. Since this PR updates the `My-Wallet-V3` submodule, you'll have to run `sh scripts/install-js.sh && …

feat(Lockbox): get data from wallet metadata (IOS-1377)

---

Blockchain/Homebrew/Exchange/Interactors/ExchangeCreateInteractor.swift

When a user inputs a value that is outside the `TradingLimits` the `secondaryAmountLabel` should show `0.00`.
When the user is above or below the `TradingLimits` we get an error. In this case we update the `secondaryAmountLabel` to show `0.00` rather than the prior (and incorrect) conversion. 
2. Go to the exchange
3. Enter in an amount above and/or below the `TradingLimits`
4. The `secondaryAmountLabel` should read `0.00`

feat(HB): Resolving IOS-1416 - UI for outside limits

---

Podfile

So that doing a `pod install` while on XCode 9 doesn't break things.
Charts, Onfido, and Starscream were not specifying the exact version that we need for it to be compatible with XCode 9 (i.e. the latest versions are build against XCode 10). Locking the specific version we need is safer, but once we upgrade to XCode 10, we can make sure to update these versions as well.

dep(Cocoapods): lock versions of Charts, Onfido, and Starscream.

---

Blockchain/Homebrew/Authentication/NabuAuthenticationService.swift
Blockchain/Homebrew/Exchange/Services/MarketsService.swift

Fixing failed ws auth errors.
Attempt # 3 for fixing the failed WS auth issue. I was able to repo the ws auth error by sending an expired token
i.e. this error
```
["description": Can not process auth request, token can not be found, "channel": auth, "type": error, "sequenceNumber": 0]
```
To circumvent this issue altogether, this PR always will request a new session token upon WS connection. I exited/re-entered the exchange screen numerous times and I was not able to repro that error anymore.
Enter/exit exchange create screen a number of times.

fix(Websocket): fix WS auth (IOS-1405)

---

Blockchain/Network/NetworkManager.swift

Restore public key pinning.
Removed whitelist from `didReceiveChallenge` delegate method.
- Go through KYC and send an exchange order on production. You should not see any "Failure to validate certificate" alerts.
- See the "Testing Certificate Pinning" section on the iOS wiki page.
N/A

fix(NetworkManager): IOS-1194 remove whitelist

---

Blockchain/Homebrew/Exchange/Controllers/ExchangeCreateViewController.storyboard

Fixes a constraint warning in the `ExchangeCreateViewController`
A view that is centered horizontally who is offset by updating the `.constant` property on said constraint cannot have leading and trailing constraints that are equal to a set amount on either side. This fixes that issue. 
2. Go to the exchange on a 5S
3. There shouldn't be a console warning.

chore(HB): fixes constraint warning.

---

Blockchain/LocalizationConstants.swift
Blockchain/Lockbox/LockboxViewController.storyboard
Blockchain/Lockbox/LockboxViewController.swift

Fixing lockbox view screen scaling issues.
* Fixed screen scaling issues with the lockbox view
* Handle action when tapping on the footer view
Tap on Lockbox side menu
iPhone 5S:
iPhone 8:

fix(Lockbox): fix small screen scaling issues (IOS-1397).

---

Blockchain/Models/Wallet.h
Blockchain/Models/Wallet.m
Blockchain/Side Menu/SideMenuPresenter.swift

Hides `Lockbox` menu item based on `accountInfo` value.
2. Go to the side menu
3. See that `Lockbox` is shown based on the value of `@"lockbox"` in the `@"invitations` dictionary of `accountInfo`.

feat(Lockbox): Hiding menu item if lockbox isn't enabled.

---

Blockchain/KYC/Information/KYCInformationViewModel.swift

Removed button for account status failed screen.
cherry-pick 710458e431b75d2e6065d4e3715acb47583abe19 to show the verification failed page when tapping on Exchange.
N/A

fix(KYCInformationViewModel): IOS-1427 hide button if accountStatus is .failed

---

Blockchain/Authentication/AuthenticationCoordinator+Pin.swift
Third Party/PinEntry/Classes/PEPinEntryController.h
Third Party/PinEntry/Classes/PEPinEntryController.m

Fix bug where biometric auth fails when you enable it right after creating a wallet.
Fix bug where biometric auth fails when you enable it right after creating a wallet.
Test the following cases:
1. create a new wallet and enable face auth
2. create a new wallet, don't enable face auth, but enable face auth in the settings screen.
N/A

fix(Biometric Auth): fix face ID bug (IOS-1433).

---

Blockchain/AppDelegate.swift
Blockchain/Network/Models/SocketMessage.swift
Blockchain/Network/SocketManager.swift

Fix issue where token expires after 5 minutes and isn't refreshed.
- `pendingSocketMessages` is an array used to store socket messages in case an attempt to send was made while the socket wasn't connected. This was not being cleared/reset properly, so multiple authentication messages were being sent, including ones that were using old session tokens. For now we clear the `pendingSocketMessages` the after `.forEach` has completed, but this should be improved on later.
- Disconnected from socket in `applicationDidEnterBackground`.
- Fixed logger typo.
- Open Exchange, leave on for > 5 minutes. You should still get conversion and rate updates.
- Open Exchange, leave on for > 5 minutes, tap sleep/wake button, go back to exchange, you should still get conversion and rate updates.
N/A

fix(Websocket Auth): fixing failed ws auth (IOS-1405, IOS-1434).

---

Blockchain/Models/Wallet.m

Fix issue where Lockbox was showing even if the wallet was not invited.
`lockbox = 0` was being converted to `YES`. Changed to convert it to `NO`.
- Create wallet with invitation status of `true`. Lockbox should show in side menu.
- Create wallet with invitation status of `false`. Lockbox should not show in side menu.
N/A

fix(Lockbox): IOS-1475 hide side menu item based on invitation status
